'use strict';
function installCorrections() {
 const set=(id,sub,html)=>{const el=document.querySelector(`#module-${id} .subtab-content[data-section="${sub}"]`);if(el)el.innerHTML=`<div class="lesson">${html}</div>`;};
 const originals=NNOriginal.tasks();
 set('task1','solution',originals[0].solution);
 set('task3','solution',NNOriginal.approximationSolution);
 set('task3','table','<h2>Stützstellen und Gewichte</h2>'+NNPractice.table(['x / RBF-Zentrum','f(x) / RBF-Gewicht','MLP-Stufengewicht'],[10,5,2,1,2,5,10,17,26].map((y,i,a)=>[i-4,y,i?y-a[i-1]:'Startwert 10']))+'<p>MLP: acht Hidden-Neuronen bei −3,…,4 und Ausgangsschwelle −10. RBF: neun Dreiecks-RBFs bei −4,…,4 mit Radius 1 und Ausgangsschwelle 0. Es sind insgesamt 10 beziehungsweise 11 Neuronen.</p>');
 set('task2','solution',originals[1].solution+'<h2>Funktionsapproximation mit RBF</h2>'+NNOriginal.approximationSolution.slice(NNOriginal.approximationSolution.indexOf('<h3>(b)')));
 set('task4','solution',NNOriginal.lvqSolution+NNOriginal.somSolution());
 set('task4','intuition',String.raw`<h2>Prototypen vertreten Bereiche des Datenraums</h2><p>Ein Codebuchvektor repräsentiert die Punkte, für die er der nächste Prototyp ist. So entstehen Voronoi-Zellen. Für die Winner-Wahl reichen quadrierte euklidische Distanzen.</p><h2>Ohne Klassen</h2><p>Nur der nächste Prototyp wird zum Datenpunkt gezogen: $r_{neu}=r+\eta(x-r)$. Für das nächste Beispiel gelten die bereits veränderten Prototypen.</p><h2>Mit Klassen: Folie 340</h2><p>Es werden die <strong>zwei nächsten Prototypen</strong> betrachtet. Haben sie verschiedene Klassen und gehört der Datenpunkt zu einer davon, wird der richtige Prototyp angezogen und der falsche abgestoßen. Andernfalls erfolgt nach dieser Regel kein Update.</p>$$r_{richtig}^{neu}=r_{richtig}+\eta(x-r_{richtig}),\qquad r_{falsch}^{neu}=r_{falsch}-\eta(x-r_{falsch}).$$<p>Die Aufgabenübersicht unterscheidet Lernen mit und ohne Klassen. Eine Variante, die nur den Gewinner nach seinem Label verändert, ist nicht die hier verwendete Regel der Folie 340.</p><h2>SOM: zusätzliche Nachbarschaft im Neuronengitter</h2><p>Der Winner wird im <strong>Datenraum</strong> gesucht. Welche weiteren Neuronen wie stark lernen, bestimmt ihr Abstand im <strong>Neuronengitter</strong>. Diese beiden Abstände nicht verwechseln.</p><p class="source">Folien 336–342, 359–366</p>`);
 set('task4','theorie',String.raw`<h2>Update-Regeln</h2><p>Unüberwachte Vektorquantisierung: Winner $u^*=\arg\min_u d(x,r_u)$, nur dieser lernt.</p>$$r_{u^*}^{neu}=r_{u^*}+\eta(x-r_{u^*}).$$<p>Überwachte Zweiprototypen-Regel: zwei nächste Referenzvektoren mit verschiedenen Klassen, von denen genau einer zum Ziel passt. Richtiger wird angezogen, falscher abgestoßen. Eine Window-Regel ist eine zusätzliche Bedingung und wird nur bei entsprechender Angabe benutzt.</p><h2>SOM</h2>$$r_u^{neu}=r_u+\eta h(d_G(u,u^*),\sigma)(x-r_u),\qquad h(d,\sigma)=e^{-d^2/(2\sigma^2)}.$$<p>Beim Winner gilt $h=1$. Für jede endliche Entfernung ist der Gaußfaktor positiv. Ein harter Abbruch nach zwei Gittereinheiten wäre eine zusätzliche, hier nicht vorgegebene Regel.</p><p class="source">Folien 336, 340–341, 364–366</p>`);
 set('task4','recipe',String.raw`<h2>Eine Epoche sauber rechnen</h2><ol><li>Ausgangsprototypen, Klassen, Lernrate und Datenreihenfolge abschreiben.</li><li>Für das aktuelle Beispiel alle Distanzen mit den aktuellen Prototypen berechnen.</li><li>Regel wählen: ohne Klassen nur Winner; nach Folie 340 die zwei nächsten Prototypen und ihre Klassenbedingungen prüfen.</li><li>Für jedes betroffene Neuron die Differenz $x-r$ bilden; mit $\eta$ multiplizieren und je nach Regel addieren oder subtrahieren.</li><li>Alle Updates dieses Beispiels aus den bisherigen Vektoren berechnen. Erst beim nächsten Beispiel neu zuordnen.</li><li>Am Ende neue Vektoren und Gesamtänderungen gegenüber dem Start angeben.</li></ol><p>Für SOM zusätzlich: Winner im Datenraum bestimmen, Gitterabstände in Gittereinheiten berechnen, für alle Neuronen den Nachbarschaftsfaktor einsetzen.</p>`);
 set('task5','intuition',String.raw`<h2>Ein rückgekoppeltes Netz</h2><p>Hopfield-Neuronen sind zugleich Ein- und Ausgabeneuronen. Die Standardannahmen hier: bipolare Zustände, symmetrische Gewichte, Diagonale null und asynchrone Aktualisierung. Ein Update verändert höchstens ein Neuron.</p><h2>Warum die Energie nicht steigt</h2>$$E(s)=-\tfrac12s^\top Ws+\theta^\top s,\qquad\Delta E=-(s_k'-s_k)(net_k-\theta_k).$$<ul><li>$net_k&lt;\theta_k$: ein Wechsel von +1 zu −1 senkt die Energie strikt.</li><li>$net_k&gt;\theta_k$: ein Wechsel von −1 zu +1 senkt sie ebenfalls strikt.</li><li>$net_k=\theta_k$: die Regel setzt +1. Ein Wechsel von −1 zu +1 hat $\Delta E=0$.</li></ul><p>Auf einem Energieplateau können echte Änderungen daher nur die Zahl der +1-Zustände erhöhen. Ein Rückweg auf demselben Plateau ist unmöglich. Zusammen mit endlich vielen Zuständen begründet dies die Konvergenz. Bei zyklischer Aktualisierung aller $n$ Neuronen in fester Reihenfolge gilt die Schranke $n2^n$ aus Folie 390.</p><div class="mistake">Aus $\Delta E\le0$ allein folgt noch kein Ausschluss von Zyklen. Dafür ist die zusätzliche Betrachtung des Gleichheitsfalls nötig. Synchrone Updates fallen nicht unter diesen Beweis.</div><h2>Assoziativer Speicher</h2><p>Hebbsche Gewichte speichern Muster über Produkte ihrer Komponenten. Mehrere Muster können einander stören; zusätzlich können unerwünschte stabile Zustände auftreten. Die Folien geben keine pauschale fehlerfreie Kapazitätsgarantie von 0.14n Mustern.</p><p><a href="#/theorie/boltzmann">Hebb, lokale Minima und Boltzmann-Maschinen</a></p><p class="source">Folien 380–390, 394–404, 422–433</p>`);
 set('deeplearning','gradient',String.raw`<h2>Vanishing Gradient</h2><p>Für die logistische Funktion gilt $f'(z)=f(z)(1-f(z))\le1/4$. Bei der Rückpropagation treten Produkte solcher Faktoren auf. Dadurch können Gradienten in frühen Schichten sehr klein werden. Die Verbindungsgewichte und die Summation über mehrere Wege wirken ebenfalls mit; eine allgemeine Schranke des gesamten Fehlersignals nur durch $(1/4)^L$ wäre unvollständig.</p><h2>Aktivierungen aus den Folien</h2><table><thead><tr><th>Funktion</th><th>Definition</th><th>Ableitung / Hinweis</th></tr></thead><tbody><tr><td>ReLU / Rampe</td><td>$\max(0,z)$</td><td>0 bei $z&lt;0$, 1 bei $z&gt;0$; bei 0 nicht klassisch differenzierbar</td></tr><tr><td>Softplus</td><td>$\ln(1+e^z)$</td><td>Logistische Funktion; stetig differenzierbar</td></tr><tr><td>Leaky ReLU</td><td>$z$ für $z&gt;0$, sonst $\nu z$</td><td>Kleine positive Steigung $\nu$ im negativen Bereich</td></tr><tr><td>Noisy ReLU</td><td>$\max(0,z+N(0,\sigma))$</td><td>Addiert Gaußrauschen</td></tr></tbody></table><p>Eine positive ReLU-Aktivierung hat keinen kleinen Sigmoid-Ableitungsfaktor. Trotzdem sind gutartige Gradienten nicht für jedes Netz garantiert. Negative ReLU-Eingaben haben weiterhin Ableitung null.</p><p class="source">Folien 249–255</p>`);
 set('deeplearning','optimizers',String.raw`<h2>Optimierer unterscheiden</h2><p>Schreibe $g_t$ für den aktuellen Gradienten. Konstante Faktoren wie Borgelts $1/2$ können in der Lernrate enthalten sein; innerhalb einer Rechnung eine Konvention beibehalten.</p><table><thead><tr><th>Verfahren</th><th>Idee und Rechenregel</th><th>Folie</th></tr></thead><tbody><tr><td>Gradientenabstieg</td><td>$\Delta w=-\eta g$</td><td>189</td></tr><tr><td>Momentum</td><td>$\Delta w_t=-\eta g_t+\alpha\Delta w_{t-1}$; nutzt die vorige Bewegung</td><td>190–191</td></tr><tr><td>Nesterov</td><td>Gradient an einer durch Momentum vorausgeschobenen Position bestimmen</td><td>190–191</td></tr><tr><td>Quickprop</td><td>$\Delta w_t=\frac{g_t}{g_{t-1}-g_t}\Delta w_{t-1}$; lokale Parabelannahme, nicht bei Nenner null definiert</td><td>192</td></tr><tr><td>Rprop</td><td>Vorzeichen bestimmt Richtung; eine eigene adaptive Schrittweite pro Parameter bestimmt die Länge</td><td>193</td></tr><tr><td>AdaGrad</td><td>Quadrierte Gradienten aufsummieren und zur Skalierung verwenden</td><td>194</td></tr><tr><td>RMSProp</td><td>Exponentiell gewichtetes Mittel quadrierter Gradienten statt unbeschränkter Summe</td><td>194</td></tr><tr><td>AdaDelta</td><td>Bezieht zusätzlich vergangene quadrierte Parameteränderungen ein</td><td>195</td></tr><tr><td>Adam</td><td>Geglättete erste und unzentrierte zweite Gradientenmomente; gegebenenfalls Bias-Korrektur</td><td>196</td></tr><tr><td>Nadam / AdaMax</td><td>Nesterov-Ergänzung zu Adam / Maximumsnorm-Variante</td><td>197–198</td></tr></tbody></table><h2>Adam: Was wird gespeichert?</h2>$$m_t=\alpha m_{t-1}+(1-\alpha)g_t,\qquad v_t=\beta v_{t-1}+(1-\beta)g_t^2,$$$$\widehat m_t=\frac{m_t}{1-\alpha^t},\qquad\widehat v_t=\frac{v_t}{1-\beta^t},\qquad\Delta w_t=-\eta\frac{\widehat m_t}{\sqrt{\widehat v_t}+\epsilon}.$$<p>Das zweite Moment ist unzentriert; es ist nicht einfach die Varianz um den Mittelwert. Die Korrektur gleicht die anfängliche Verzerrung durch $m_0=v_0=0$ aus.</p><details><summary>Ein Momentum-Schritt</summary><p>$g_t=2$, $\eta=0.1$, $\alpha=0.9$, $\Delta w_{t-1}=-0.05$. Dann $\Delta w_t=-0.2-0.045=-0.245$. Bei $w_t=1$ wird $w_{t+1}=0.755$.</p></details>`);
 // Correct old recall/MC entries in the same model used by all trainers.
 const q=Object.fromEntries(mcqData.flatMap(g=>g.statements).map(s=>[s.id,s]));
 q.a1.slide='Folien 174–183';
 q.a4.text='Self-Organizing Maps train a neighborhood-preserving representation on a low-dimensional neuron grid.';
 q.a4.expl='SOM trainiert Winner und benachbarte Gitterneuronen gemeinsam. Dadurch wird eine topologieerhaltende Darstellung angestrebt; perfekte Topologieerhaltung für beliebige Daten ist keine Garantie.';
 q.c4.text='With enough hidden units and a suitable nonlinear activation, a three-layer perceptron can uniformly approximate a continuous function on a compact domain.';
 q.c4.slide='Folien 99, 104';q.c4.expl='Der Definitionsbereich ist kompakt, die Zielfunktion stetig. Genügend Hidden-Neuronen und geeignete Aktivierungen sind erforderlich. Es geht um Existenz, nicht um den Erfolg eines Trainingslaufs.';
 q.e2.expl='Eine Metrik erfüllt Identität, Symmetrie und Dreiecksungleichung. Assoziativität ist kein Metrikaxiom; auf allgemeinen Punkträumen ist ein Abstand als erneutes Punktargument nicht einmal definiert.';
 Object.assign(q.c2,{text:'Ein MLP mit geeigneter nichtlinearer Hidden-Aktivierung kann stetige Funktionen auf kompakten Mengen beliebig genau approximieren.',correct:true,slide:'Folie 104',expl:'Stetige, beschränkte, nichtkonstante Aktivierung; genügend Hidden-Neuronen; linearer Ausgang. Der Satz ist eine Existenzaussage und keine Trainingsgarantie.'});
 Object.assign(q.c3,{text:'Jede in den Folien behandelte radiale Aktivierungsfunktion ist außerhalb eines endlichen Radius exakt null.',correct:false,slide:'Folie 291',expl:'Rechteck und Dreieck haben beschränkten Träger. Eine Gaußfunktion ist dagegen bei jedem endlichen Abstand positiv; sie fällt nur gegen null ab.'});
 q.d4.slide='Folie 193';q.d5.slide='Folie 194';q.d2.expl='Adam schätzt das erste und das unzentrierte zweite Gradientenmoment. Die Bias-Korrektur gleicht die Initialisierung mit null aus (Folie 196).';
 q.f3.expl='Bei sofortiger erneuter Aktualisierung desselben Neurons sind seine Eingaben unverändert: keine Selbstkopplung, andere Zustände unverändert. Deshalb wird derselbe neue Wert erneut berechnet. Ein strikter Energieabfall ist dafür nicht nötig.';
 q.f5.text='Bei zyklischer asynchroner Aktualisierung aller Neuronen in fester Reihenfolge erreicht das Standard-Hopfield-Netz einen stabilen Zustand.';q.f5.slide='Folien 388–390';q.f5.expl='Unter den Standardannahmen und der angegebenen Schwellenregel gilt die Konvergenz. Die Schranke n·2ⁿ Einzelupdates bezieht sich auf die feste zyklische Reihenfolge.';
 for(const s of Object.values(q))if(s.slide==='Folie 332')s.slide='Folie 333';
 for(const t of theoryEntries){
  if(t.id==='hornik-approx'){t.source='Folie 104';t.text=String.raw`Für stetige Funktionen auf kompakten Mengen existiert zu jeder positiven Fehlerschranke eine Approximation durch ein Netz mit genügend Hidden-Neuronen, stetiger, beschränkter und nichtkonstanter Hidden-Aktivierung sowie linearem Ausgang. Der maximale Fehler kann beliebig klein werden. Der Satz garantiert weder das Finden dieser Gewichte beim Training noch die Generalisierung.`;}
  if(t.id==='hopfield-hebb'){t.source='Folien 394–404';t.text=String.raw`Hebbsche Speicherung: $w_{ij}=\sum_p s_i^{(p)}s_j^{(p)}$ für $i\ne j$, $w_{ii}=0$. Anschließend die gewünschten Muster auf Stabilität prüfen. Überlagerungen können zu Fehlern und zusätzlichen Attraktoren führen. Bei einem einzelnen bipolaren Muster und Schwellen null ist auch das negative Muster stabil.`;t.checks=['Diagonale null.','Muster komponentenweise multiplizieren und aufsummieren.','Stabilität anschließend prüfen.'];}
  if(t.id==='metric-axioms')t.source='Folien 289, 333';
  if(t.id.includes('lvq')){t.text=String.raw`Ohne Klassen: nächsten Prototyp mit $r'=r+\eta(x-r)$ anpassen. Mit Klassen nach Folie 340: zwei nächste Prototypen betrachten; bei verschiedenen Labels und einem passenden Label den richtigen anziehen, den falschen abstoßen. Für das nächste Datenbeispiel die aktualisierten Prototypen verwenden.`;t.source='Folien 336, 340–341';t.checks=['Welche Regel ist angegeben?','Ein oder zwei Prototypen?','Bei jedem neuen Datenpunkt neu zuordnen.'];}
  if(t.id.includes('energy')){t.text=String.raw`Für symmetrische Gewichte, Diagonale null und asynchrone Updates gilt $E=-\frac12s^\top Ws+\theta^\top s$ und $\Delta E=-(s_i'-s_i)(net_i-\theta_i)\le0$. Bei $net_i=\theta_i$ kann −1 zu +1 wechseln, ohne Energieabfall. Auf einem Plateau nimmt bei echten Änderungen nur die Zahl der +1-Werte zu. Dies schließt Rückkehrzyklen aus; bei zyklischer Reihenfolge werden höchstens $n2^n$ Updates benötigt.`;t.source='Folien 388–390';t.checks=['Asynchron, symmetrisch, Diagonale null.','Gleichheitsfall begründet.','Keine Garantie eines globalen Minimums.'];}
 }
}
