'use strict';
function initStudyExam() {
 const section=document.getElementById('module-klausur');
 let timer;
 const valid=e=>e&&e.version===1&&['original','variant','extended'].includes(e.mode)&&Number.isInteger(e.seed)&&['running','finished'].includes(e.status)&&Number.isFinite(e.deadline);
 if(!valid(state.exam))state.exam=null;
 function buildTasks(e){
  if(e.mode==='original')return NNOriginal.tasks();
  const types=e.mode==='extended'?['regression','klassifikation','backprop','lvq','hopfield']:['tlu','rbf','approximation','lvq','hopfield'];
  return types.map((type,i)=>{const q=NNPractice.make(type,e.seed+i*17);let prompt=q.prompt,solution=q.solution;
   if(type==='lvq'){const som=NNPractice.make('som',e.seed+71);prompt+='<br><br><strong>Teil b: SOM.</strong> '+som.prompt;solution+='<h3>Teil b: SOM</h3>'+som.solution;}
   return {...q,prompt,solution,rubric:type==='lvq'?[['LVQ ohne Klassen',3],['LVQ mit Klassen',5],['SOM: Gitter und Update',6]]:[['Ansatz und Voraussetzungen',3],['Vollständiger Rechenweg / Konstruktion',6],['Ergebnisse und Parameter',3],['Begründung und Kontrolle',2]]};
  });
 }
 function render(){
  clearInterval(timer);
  const e=state.exam;
  if(!e){section.innerHTML='<h1>120-Minuten-Klausurtraining</h1><p class="learning-intro">Fünf Rechenaufgaben und sechs MC-Blöcke. Rechne auf Papier oder in den Notizfeldern. Lösungen werden erst beim Abgeben sichtbar.</p><p class="exam-warning">Die Verteilung 5 × 14 + 30 Punkte ist ein Trainingsschema. Die MC-Regel entspricht Folie 2. Eine offizielle Bestehensgrenze ist nicht angegeben.</p><div class="practice-card"><label for="exam-mode">Aufgabenauswahl</label><select id="exam-mode"><option value="original">Aufgabenübersicht 2024 · Originalzahlen</option><option value="variant">Gleiche Aufgabenfamilien · neue Zahlen</option><option value="extended">Folienstoff · mit Regression und Klassifikation</option></select><p>Bei „Originalzahlen“ sind die MC-Aussagen aus den Themenstichworten rekonstruiert. Die beiden anderen Modi sind eigene Trainingsklausuren.</p><button class="primary" id="study-exam-start">120 Minuten starten</button></div><p>Die Uhr läuft auch weiter, wenn du ein anderes Kapitel öffnest oder die Seite neu lädst. Der Stand wird in diesem Browser gespeichert.</p>';section.querySelector('button').addEventListener('click',()=>{const seed=Date.now()%1000000;state.exam={version:1,mode:section.querySelector('select').value,seed,status:'running',deadline:Date.now()+120*60000,answers:{},notes:{},points:{}};saveState();render();});return;}
  const tasks=buildTasks(e),groups=selectQuestionGroups(e.seed,e.mode==='original'?'core':'mixed'),finished=e.status==='finished';
  e.answers=e.answers&&typeof e.answers==='object'?e.answers:{};e.notes=e.notes&&typeof e.notes==='object'?e.notes:{};e.points=e.points&&typeof e.points==='object'?e.points:{};
  section.innerHTML=`<h1>120-Minuten-Klausurtraining</h1><div class="exam-bar"><strong id="study-clock" aria-label="Verbleibende Zeit"></strong><span>${finished?'Abgegeben':e.mode==='original'?'Aufgabenübersicht 2024':'Eigene Trainingsklausur'} · ${e.seed}</span><button id="study-exam-action" class="primary">${finished?'Neue Klausur vorbereiten':'Abgeben und Lösungen öffnen'}</button></div>${finished?'<p class="exam-warning">Bewerte die Rechenaufgaben selbst anhand der Teilkriterien. Der MC-Teil wird automatisch bewertet. Das Ergebnis ist eine Übungsbewertung und keine Bestehenszusage.</p><p id="study-exam-total" class="learning-goals" role="status"></p>':'<p>Die Lösungen bleiben bis zur Abgabe verdeckt. Der Timer läuft beim Wechsel zu anderen Kapiteln weiter.</p>'}<div class="lesson">${tasks.map((q,i)=>`<article class="practice-card"><p class="source">${q.source} · 14 Trainingspunkte</p><h2>${i+1}. ${q.title}</h2><p>${q.prompt}</p>${q.image?`<img src="${q.image}" alt="Abbildung zu ${q.title} aus der Aufgabenübersicht 2024" style="max-width:100%;max-height:320px">`:''}<label for="exam-work-${i}">Eigener Lösungsweg</label><textarea id="exam-work-${i}" data-exam-note="${i}" rows="5" ${finished?'readonly':''}></textarea>${finished?`<details><summary>Musterlösung und Bewertung</summary>${q.solution}<h3>Selbstbewertung</h3>${q.rubric.map(([label,max],j)=>`<label for="exam-score-${i}-${j}">${label} (0–${max}) <input type="number" min="0" max="${max}" step="1" value="${Number.isFinite(Number(e.points[i+'-'+j]))?Math.max(0,Math.min(max,Number(e.points[i+'-'+j]))):0}" id="exam-score-${i}-${j}" data-rubric="${i}-${j}" data-max="${max}"></label>`).join('')}</details>`:''}</article>`).join('')}<h2>6. Multiple Choice · 30 Punkte</h2>${questionBlocksHTML(groups,e.answers,finished,'exam')}</div>`;
  section.querySelectorAll('[data-exam-note]').forEach(ta=>{ta.value=String(e.notes[ta.dataset.examNote]||'');ta.addEventListener('input',()=>{if(e.status==='running'){e.notes[ta.dataset.examNote]=ta.value;saveState();}});});
  section.querySelectorAll('[data-question]').forEach(input=>input.addEventListener('change',()=>{if(e.status==='running'){e.answers[input.dataset.question]=input.value;saveState();}}));
  section.querySelectorAll('[data-rubric]').forEach(input=>input.addEventListener('input',()=>{const n=Math.max(0,Math.min(Number(input.dataset.max),Math.round(Number(input.value)||0)));input.value=n;e.points[input.dataset.rubric]=n;saveState();score(tasks,groups);}));
  section.querySelector('#study-exam-action').addEventListener('click',()=>{if(e.status==='running'){if(confirm('Klausur abgeben? Danach werden Lösungen sichtbar und die Antworten festgehalten.'))finish();}else{state.examHistory=Array.isArray(state.examHistory)?state.examHistory:[];state.examHistory.push({...e});state.examHistory=state.examHistory.slice(-10);state.exam=null;saveState();render();}});
  function tick(){const ms=Math.max(0,e.deadline-Date.now()),sec=Math.ceil(ms/1000),clock=section.querySelector('#study-clock');clock.textContent=finished?'Auswertung':`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;if(!finished&&ms===0)finish();}
  renderMath(section);if(finished)score(tasks,groups);tick();if(e.status==='running')timer=setInterval(tick,1000);
 }
 function score(tasks,groups){const e=state.exam,mc=scoreQuestionGroups(groups,e.answers).reduce((s,g)=>s+g.score,0);let calc=0;tasks.forEach((t,i)=>t.rubric.forEach(([,max],j)=>{calc+=Math.max(0,Math.min(max,Math.round(Number(e.points[i+'-'+j])||0)));}));section.querySelector('#study-exam-total').textContent=`${calc+mc} / 100 Trainingspunkte · Rechnen: ${calc}/70 (Selbstbewertung) · MC: ${mc}/30`;state.scores['exam-'+e.seed]=calc+mc;saveState();}
 function finish(){if(state.exam&&state.exam.status==='running'){state.exam.status='finished';state.exam.finishedAt=Date.now();saveState();render();}}
 render();
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.exam?.status==='running'&&Date.now()>=state.exam.deadline)finish();});
}
