'use strict';
// Deterministic variants, shared by practice and the exam. All values are local.
const NNPractice = (() => {
  const f = n => Math.abs(n) < 1e-10 ? '0' : Number(n.toFixed(4)).toString();
  const vec = v => `(${v.map(f).join(', ')})`;
  const field = (label, answer, tolerance=.002) => ({label,answer,tolerance});
  const table = (head, rows) => `<div class="table-scroll"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const dist2 = (a,b) => a.reduce((s,x,i)=>s+(x-b[i])**2,0);
  const sigmoid = z => z>=0 ? 1/(1+Math.exp(-z)) : Math.exp(z)/(1+Math.exp(z));
  function rng(seed) { let s=Number(seed)>>>0; return () => {s=(s+0x6D2B79F5)>>>0;let t=Math.imul(s^(s>>>15),1|s);t^=t+Math.imul(t^(t>>>7),61|t);return ((t^(t>>>14))>>>0)/4294967296;}; }
  function hopfield(weights, theta) {
    return Array.from({length:8},(_,k)=>{
      const s=[(k&4)?1:-1,(k&2)?1:-1,(k&1)?1:-1];
      const net=s.map((_,i)=>weights[i].reduce((a,w,j)=>a+w*s[j],0));
      const successors=net.map((n,i)=>{const t=[...s];t[i]=n>=theta[i]?1:-1;return t;});
      const energy=-.5*s.reduce((a,x,i)=>a+x*net[i],0)+s.reduce((a,x,i)=>a+x*theta[i],0);
      return {state:s,net,successors,energy,stable:successors.every(t=>t.every((v,i)=>v===s[i]))};
    });
  }
  function make(type, seed=1) {
    const random=rng(seed), integer=(a,b)=>a+Math.floor(random()*(b-a+1));
    const base={type,seed,checks:['Ansatz und eingesetzte Größen sind angegeben.','Zwischenschritte und Ergebnis sind nachvollziehbar.'],hints:[]};
    let q;
    switch(type) {
      case 'regression': {
        const a=integer(-2,4), b=integer(1,4), e=integer(1,3);
        const xs=[0,1,2],ys=[a+e,a+b-2*e,a+2*b+e],sumY=ys.reduce((s,x)=>s+x,0),sumXY=ys[1]+2*ys[2],sse=6*e*e;
        q={title:'Eine Regressionsgerade aus Daten',source:'Folien 109–112',prompt:String.raw`Bestimme die Least-Squares-Gerade $g(x)=a+bx$ zu ${xs.map((x,i)=>vec([x,ys[i]])).join(', ')}. Stelle die Normalgleichungen auf und berechne die Fehlerquadratsumme $F$.`,fields:[field('Achsenabschnitt a',a),field('Steigung b',b),field('Fehlerquadratsumme F',sse)],hints:['Tabelliere x, y, x² und xy.','Die Gleichungen lauten 3a + 3b = Σy und 3a + 5b = Σxy.'],solution: String.raw`<p>$\sum x=3$, $\sum x^2=5$, $\sum y=${sumY}$, $\sum xy=${sumXY}$.</p>$$3a+3b=${sumY},\quad3a+5b=${sumXY}.$$<p>Subtrahieren liefert $2b=${2*b}$, also $b=${b}$ und $a=${a}$. Residuen: ${vec([-e,2*e,-e])}. Somit $F=${sse}$ und $\mathrm{MSE}=${2*e*e}$.</p>`};break;
      }
      case 'polynom': {
        const a=integer(-2,3),b=integer(1,4),c=integer(1,3);const y=[a-b+c,a,a+b+c];
        q={title:'Polynomiale Regression',source:'Folien 113–119',prompt:String.raw`Finde $g(x)=a_0+a_1x+a_2x^2$ für die Punkte $(-1,${y[0]}),(0,${y[1]}),(1,${y[2]})$. Schreibe die Designmatrix und die Normalgleichungen auf.`,fields:[field('a₀',a),field('a₁',b),field('a₂',c)],hints:['Die Zeilen von X lauten (1,x,x²).','Bei x=0 folgt a₀ direkt. Subtrahiere anschließend die Gleichungen für x=1 und x=−1.'],solution:String.raw`$$X=\begin{pmatrix}1&-1&1\\1&0&0\\1&1&1\end{pmatrix},\quad X^\top X=\begin{pmatrix}3&0&2\\0&2&0\\2&0&2\end{pmatrix},\quad X^\top y=\begin{pmatrix}${3*a+2*c}\\${2*b}\\${2*a+2*c}\end{pmatrix}.$$<p>Die Lösung ist $(a_0,a_1,a_2)=${vec([a,b,c])}$. Einsetzen trifft alle drei Punkte; die Fehlerquadratsumme ist null. $X$ hat vollen Rang.</p>`};break;
      }
      case 'logit': {
        const odds=integer(2,5);q={title:'Logit-Transformation',source:'Folien 123–129',prompt:String.raw`Eine logistische Funktion mit $Y=1$ soll durch $(0,1/2)$ und $(1,${odds}/${odds+1})$ gehen. Bestimme die Koeffizienten von $z=a_0+a_1x$ nach der Logit-Transformation und berechne $g(2)$.`,fields:[field('a₀',0),field('a₁',Math.log(odds)),field('g(2)',odds**2/(1+odds**2))],hints:['z = ln(y/(1−y)).','Die transformierten Punkte sind (0,0) und (1,ln r).'],solution:String.raw`<p>Bei $x=0$ ist der Logit $\ln1=0$. Bei $x=1$ ist er $\ln${odds}$. Also $a_0=0$, $a_1=\ln${odds}\approx${f(Math.log(odds))}$.</p>$$g(2)=\frac1{1+e^{-2\ln${odds}}}=\frac{${odds**2}}{${1+odds**2}}\approx${f(odds**2/(1+odds**2))}.$$<p>Die Transformation setzt Zielwerte strikt zwischen 0 und 1 voraus.</p>`};break;
      }
      case 'klassifikation': {
        const a0=integer(-3,0), a1=integer(1,3),a2=-integer(1,2),x=[integer(0,3),integer(0,3)],z=a0+a1*x[0]+a2*x[1],p=sigmoid(z);
        q={title:'Logistische Entscheidung',source:'Folien 139–140',prompt:String.raw`Gegeben ist $z=${a0}+${a1}x_1${a2}x_2$ und $p_1=1/(1+e^{-z})$. Bestimme für $x=${vec(x)}$ den Wert $z$, die Wahrscheinlichkeit für Klasse 1 und die Klasse bei Schwelle $1/2$. Gib außerdem die Entscheidungsgrenze an.`,fields:[field('z',z),field('p₁',p),field('Klasse (0 oder 1)',z>=0?1:0,0)],hints:['Zuerst die affine Funktion auswerten.','p₁ ≥ 1/2 ist gleichbedeutend mit z ≥ 0.'],solution:String.raw`<p>$z=${a0}+${a1}\cdot${x[0]}${a2}\cdot${x[1]}=${z}$, $p_1=${f(p)}$, $p_0=${f(1-p)}$. Klasse ${z>=0?1:0}.</p><p>Die Entscheidungsgrenze ist $${a0}+${a1}x_1${a2}x_2=0$. Für die Klassenseite einen Testpunkt einsetzen. Bei $z=0$ wählen wir gemäß der angegebenen $\ge$-Regel Klasse 1.</p>`};break;
      }
      case 'bce': {
        const p=integer(2,8)/10,y=integer(0,1),x=integer(1,4),loss=-(y?Math.log(p):Math.log(1-p));
        q={title:'BCE und Gradienten-Schritt',source:'Folien 152–162',prompt:String.raw`Ein Modell liefert für $x=${x}$ die Wahrscheinlichkeit $p=${p}$ für Klasse 1. Das Ziel ist $y=${y}$. Berechne die BCE mit natürlichem Logarithmus und die Änderungen von Bias $a_0$ und Gewicht $a_1$ bei Gradientenaszendenz auf die Log-Likelihood mit $\eta=0.1$.`,fields:[field('BCE',loss),field('Δa₀',.1*(y-p)),field('Δa₁',.1*(y-p)*x)],hints:['Für y=1: −ln p; für y=0: −ln(1−p).','Δa = η(y−p)(1,x).'],solution:String.raw`<p>$\mathrm{BCE}=${y?' -\ln('+p+')':'-\ln('+(1-p).toFixed(1)+')'}=${f(loss)}$. Der Fehlerfaktor ist $y-p=${f(y-p)}$.</p>$$\Delta a=0.1\cdot${f(y-p)}\binom1{${x}}=\binom{${f(.1*(y-p))}}{${f(.1*(y-p)*x)}}.$$<p>Dies ist ein Update auf die Log-Likelihood. Für quadratischen Fehler wäre zusätzlich der Ableitungsfaktor $p(1-p)$ zu berücksichtigen.</p>`};break;
      }
      case 'softmax': {
        const v=[1,integer(2,4),integer(5,8)],s=v.reduce((a,b)=>a+b,0),target=integer(0,2);q={title:'Softmax und Kreuzentropie',source:'Folien 164–170',prompt:String.raw`Die Aktivierungen sind $z=(\ln${v[0]},\ln${v[1]},\ln${v[2]})$. Berechne die drei Softmax-Wahrscheinlichkeiten und die Kreuzentropie zur wahren Klasse ${target+1}. Verwende $\log_2$.`,fields:[...v.map((n,i)=>field(`p${i+1}`,n/s)),field('Kreuzentropie (Basis 2)',-Math.log2(v[target]/s))],hints:['Nach dem Exponenzieren bleiben die drei angegebenen Zahlen.','Bei einem One-Hot-Ziel bleibt nur −log₂ der Wahrscheinlichkeit der wahren Klasse.'],solution:String.raw`<p>Der Nenner ist $${v.join('+')}=${s}$. Somit $p=${vec(v.map(x=>x/s))}$. Die Summe ist 1.</p>$$H=-\log_2\frac{${v[target]}}{${s}}=${f(-Math.log2(v[target]/s))}.$$<p>Die Vorhersage ist Klasse 3; die wahre Klasse ${target+1} ist separat gegeben.</p>`};break;
      }
      case 'tlu': {
        const tx=integer(-1,2),ty=integer(-1,2);const p=[[1+tx,4+ty],[4+tx,4+ty],[3+tx,1+ty],[3+tx,3+ty]];
        const th=[-4-ty,9+tx+2*ty,-8-3*tx+ty,-3-tx,3+tx];
        q={title:'Dreischichtiges TLU-Netz',source:'Aufgabe 1 (2024), übersetzte Variante · Folien 17–35',prompt:String.raw`Die Polygonpunkte in Umlaufrichtung sind ${p.map(vec).join(', ')}. Konstruiere ein Netz mit Ausgabe 1 im Polygon und 0 außerhalb. Zerlege bei $x_1=${3+tx}$. Verwende für die fünf Halbebenen die Normalen $(0,-1),(1,2),(-3,1),(-1,0),(1,0)$ und die Regel $w^\top x\ge\theta$. Bestimme alle Schwellen und die AND-/OR-Schichten.`,fields:th.map((x,i)=>field(`θ${i+1}`,x)),hints:['Die obere Kante begrenzt x₂ nach oben. Multipliziere ihre Ungleichung mit −1.','Linkes Dreieck: L₁ ∧ L₂ ∧ L₄. Rechtes Dreieck: L₁ ∧ L₃ ∧ L₅.'],solution:String.raw`<p>Die Schwellen in der vorgegebenen Reihenfolge sind $${vec(th)}$. Jede Normale zeigt in den gewünschten Halbraum.</p><p>Schicht 2: $C_1=L_1\wedge L_2\wedge L_4$ und $C_2=L_1\wedge L_3\wedge L_5$. Jeweils Gewichte $(1,1,1)$ und Schwelle 3. Schicht 3: $Y=C_1\vee C_2$, Gewichte $(1,1)$ und Schwelle 1.</p><p>Prüfe mindestens einen Punkt in jedem Dreieck und einen Punkt in der ausgesparten Ecke. Die Teilungslinie darf zu beiden Dreiecken gehören.</p>`,checks:['Alle fünf Normalen und Schwellen sind angegeben.','AND-Verknüpfungen und abschließendes OR sind gezeichnet.','Innen- und Außenpunkte wurden geprüft.']};break;
      }
      case 'rbf': {
        const cx=integer(1,4),cy=integer(1,4),r=integer(1,3);q={title:'RBF-Fläche mit Minkowski-Metriken',source:'Aufgabe 2 (2024), skalierte/verschobene Variante · Folien 288–291',prompt:String.raw`Die Zielfläche besteht aus zwei Dreiecken mit gemeinsamer Spitze $c=${vec([cx,cy])}$: das erste hat weitere Ecken $${vec([cx+r,cy])}$ und $${vec([cx,cy+r])}$, das zweite $${vec([cx-r,cy])}$ und $${vec([cx,cy-r])}$. Ränder sind egal. Konstruiere $y=1$ innen und $y\le0$ außen. Nutze eine L₁-Raute und zwei L∞-Quadrate zum Abziehen.`,fields:[field('Radius der Raute',r),field('Radius der Quadrate',r/2),field('x-Koordinate des linken oberen Quadratzentrums',cx-r/2),field('y-Koordinate dieses Zentrums',cy+r/2)],hints:['Ein L₁-Ball ist eine Raute. Die falschen Quadranten sind links oben und rechts unten.','Die Quadratzentren liegen relativ zur gemeinsamen Spitze bei (−r/2,+r/2) und (+r/2,−r/2).'],solution:String.raw`<p>Hidden 1: Zentrum $${vec([cx,cy])}$, $L_1$, Radius $${r}$. Hidden 2: Zentrum $${vec([cx-r/2,cy+r/2])}$, $L_\infty$, Radius $${r/2}$. Hidden 3: Zentrum $${vec([cx+r/2,cy-r/2])}$, $L_\infty$, Radius $${r/2}$.</p><p>Alle verwenden die Rechteckaktivierung $h_j=1$ für $d_j\le\sigma_j$, sonst 0. Ausgabe: $y=h_1-h_2-h_3$, lineare Aktivierung, Schwelle 0, Identität als Ausgabefunktion.</p><p>Im gewünschten Inneren ist nur $h_1=1$. In den ausgesparten Teilen kompensiert ein Quadrat die Raute. Außerhalb der Raute ist $h_1=0$ und die Ausgabe daher nie positiv.</p>`,checks:['Zentren, Metriken und Radien vollständig.','Rechteckaktivierung und lineare Ausgabe definiert.','Die drei räumlichen Fälle sind begründet.']};break;
      }
      case 'approximation': {
        const a=integer(1,3),b=integer(-2,2),c=integer(1,4),fun=x=>a*x*x+b*x+c,ys=Array.from({length:9},(_,i)=>fun(i-4)),d=ys.slice(1).map((y,i)=>y-ys[i]);
        q={title:'Eine Funktion mit MLP und RBF approximieren',source:'Aufgabe 3 (2024), Polynomvariante · Folien 99–104, 291–298',prompt:String.raw`Approximiere $f(x)=${a}x^2${b>=0?'+':''}${b}x+${c}$ auf $[-4,4]$ mit insgesamt 8 bis 12 Neuronen. (a) MLP mit 8 Stufen bei −3,…,4. (b) RBF mit 9 Dreiecksfunktionen an den Zentren −4,…,4 und Radius 1. Gib alle Gewichte, Aktivierungen und Biaswerte an; nenne zwei Verbesserungen.`,fields:[field('MLP-Startwert f(−4)',ys[0]),field('Erstes MLP-Ausgabegewicht Δy₁',d[0]),field('Letztes MLP-Ausgabegewicht Δy₈',d[7]),field('Erstes RBF-Ausgabegewicht (Zentrum −4)',ys[0])],hints:['MLP-Gewichte sind Differenzen aufeinanderfolgender Funktionswerte.','RBF: hᵢ(x)=max(0,1−|x−cᵢ|), wᵢ=f(cᵢ). Zwischen benachbarten Zentren summieren sich die zwei aktiven Basisfunktionen zu 1.'],solution:table(['xᵢ / cᵢ','f(xᵢ) / RBF-Gewicht','MLP-Stufengewicht'],ys.map((v,i)=>[i-4,v,i?d[i-1]:'Startwert']))+String.raw`<p>MLP: Eingangsgewichte 1, $h_i(x)=\mathbf1_{x\ge x_i}$ bei $x_i=-3,\ldots,4$. $\widehat f(x)=${ys[0]}+\sum_{i=1}^{8}\Delta y_i h_i(x)$. Linearer Ausgang mit $\theta=${-ys[0]}$; insgesamt 1+8+1=10 Neuronen.</p><p>RBF: $h_i(x)=\max(0,1-|x-c_i|)$ mit $c_i=-4,\ldots,4$. $\widehat f(x)=\sum_{i=0}^{8}f(c_i)h_i(x)$, Ausgangsschwelle 0. Insgesamt 1+9+1=11 Neuronen. Diese Näherung interpoliert alle Stützstellen und ist dazwischen linear. An einem Zentrum sind die benachbarten Dreiecksfunktionen null.</p><p>Verbesserungen: feinere Unterteilung durch mehr Neuronen, sofern die Knotengrenze entfällt; oder andere Aktivierungen mit erneut angepassten Parametern und geprüftem Approximationsfehler. Aktivierungen bei unveränderten Gewichten auszutauschen garantiert keine Verbesserung.</p>`,checks:['Alle Gewichte und Aktivierungen angegeben.','Ausgangsschwelle und Gesamtknotenzahl stimmen.','Stützstellen und Zwischenpunkte geprüft.']};break;
      }
      case 'lvq': {
        const offset=integer(-2,2),p=[1+offset,6],qv=[9+offset,1],initial=[[5+offset,4],[7+offset,5]],eta=.5;
        function train(supervised) {const centers=initial.map(x=>[...x]),rows=[];for(const [j,x] of [p,qv].entries()){const ds=centers.map(c=>dist2(c,x)),win=ds[0]<=ds[1]?0:1,old=centers.map(c=>[...c]);for(let k=0;k<2;k++)if(supervised||k===win){const sign=supervised&&k!==j?-1:1;centers[k]=old[k].map((v,i)=>v+sign*eta*(x[i]-v));}rows.push([j?'q':'p',ds.map(f).join(' / '),win===0?'A':'B',vec(centers[0]),vec(centers[1])]);}return {centers,rows};}
        const uns=train(false),sup=train(true);
        q={title:'LVQ: mit und ohne Klassen',source:'Aufgabe 4a (2024), verschobene Variante · Folien 336, 340',prompt:String.raw`Start: Prototyp A der Klasse A bei $${vec(initial[0])}$, Prototyp B der Klasse B bei $${vec(initial[1])}$. Daten: zuerst $p=${vec(p)}$ aus Klasse A, dann $q=${vec(qv)}$ aus Klasse B. Lernrate 0.5. Berechne eine Epoche ohne Klassen (nur Winner) und mit Klassen nach Folie 340 (zwei nächste Prototypen, richtigen anziehen und falschen abstoßen). Starte beide Fälle bei den ursprünglichen Prototypen.`,fields:[field('Ohne Klassen: Endwert x von A',uns.centers[0][0]),field('Ohne Klassen: Endwert y von B',uns.centers[1][1]),field('Mit Klassen: Endwert x von A',sup.centers[0][0]),field('Mit Klassen: Endwert y von B',sup.centers[1][1])],hints:['Ohne Klassen entscheidet allein der kleinste Abstand.','Mit Klassen sind hier beide Prototypen betroffen: ihre Klassen sind verschieden und eine stimmt mit dem Datenpunkt überein. Verwende für q die Ergebnisse nach p.'],solution:'<h4>Ohne Klassen</h4>'+table(['Punkt','d² zu A / B','Winner','A danach','B danach'],uns.rows)+'<h4>Mit Klassen</h4>'+table(['Punkt','d² zu A / B','Nächster','A danach','B danach'],sup.rows)+String.raw`<p>Bei p: A anziehen, B abstoßen. Bei q: B anziehen, A abstoßen. Updates: $r'=r\pm\eta(x-r)$. Es wurde keine zusätzliche Window-Bedingung vorgegeben.</p>`,data:{initial,points:[p,qv],unsupervised:uns.centers,supervised:sup.centers}};break;
      }
      case 'som': {
        const x=[integer(20,28),20],winner=[30,20],neighbor=[30,24],eta=.5,sigma=2,h=Math.exp(-1/(2*sigma*sigma)),newW=winner.map((v,i)=>v+eta*(x[i]-v)),newN=neighbor.map((v,i)=>v+eta*h*(x[i]-v));
        q={title:'SOM: Datenraum und Gitter',source:'Aufgabe 4b (2024), Teilnetzvariante · Folien 359–366',prompt:String.raw`Für $x=${vec(x)}$ ist der Winner $r_*=${vec(winner)}$ gegeben. Ein Nachbar mit Prototyp $r=${vec(neighbor)}$ hat Gitterabstand 1 zum Winner. Berechne beide Updates mit $\eta=0.5$ und $\sigma=2$.`,fields:[field('Nachbarschaftsfaktor h für den Nachbarn',h),field('Neues x des Winners',newW[0]),field('Neues x des Nachbarn',newN[0]),field('Neues y des Nachbarn',newN[1])],hints:['h = exp(−d_Gitter²/(2σ²)). Beim Winner ist d_Gitter=0.','Für jedes Neuron r_neu = r + η h (x−r).'],solution:String.raw`<p>Winner: $h_*=1$, also $r_*^{neu}=${vec(newW)}$.</p>$$h=e^{-1/8}\approx${f(h)},\qquad\eta h\approx${f(eta*h)}.$$<p>Nachbar: $r^{neu}=${vec(neighbor)}+${f(eta*h)}\,${vec(x.map((v,i)=>v-neighbor[i]))}=${vec(newN)}$.</p><p>Der Gitterabstand beschreibt Positionen der Neuronen im Ausgabegitter. Er ist nicht die euklidische Distanz zwischen ihren Prototypen im Datenraum.</p>`};break;
      }
      case 'hopfield': {
        const k=integer(1,3),weights=[[0,-k,0],[-k,0,-k],[0,-k,0]],theta=[-1,-2,-1],rows=hopfield(weights,theta),sign=v=>v.map(x=>x>0?'+':'−').join('');
        q={title:'Vollständiger Hopfield-Zustandsgraph',source:'Aufgabe 5 (2024), Gewichtsvariante · Folien 380–390',prompt:String.raw`Drei bipolare Neuronen: $w_{12}=w_{21}=-${k}$, $w_{23}=w_{32}=-${k}$, $w_{13}=w_{31}=0$, $w_{ii}=0$, $\theta=(-1,-2,-1)$. Aktualisiere asynchron mit $s_i'=+1$ für $\mathrm{net}_i\ge\theta_i$, sonst −1. Zeichne alle Zustände und für jeden Zustand die Nachfolger beim Update von 1, 2 und 3.`,fields:[field('Anzahl stabiler Zustände',rows.filter(x=>x.stable).length,0),field('Energie von (−1,−1,−1)',rows[0].energy),field('Energie von (+1,−1,+1)',rows[5].energy)],hints:['Es gibt 2³=8 Zustände. Pro Ausgangszustand drei einzelne Updates prüfen, nicht alle Neuronen gleichzeitig ändern.','E = −½ sᵀWs + θᵀs. Beim asynchronen Update werden die anderen zwei Werte beibehalten.'],solution:table(['Zustand','net₁,net₂,net₃','Update 1','Update 2','Update 3','E','stabil'],rows.map(r=>[sign(r.state),vec(r.net),...r.successors.map(sign),r.energy,r.stable?'ja':'nein']))+`<p>Zeichne für jede Tabellenzeile die drei gerichteten Kanten. Selbstnachfolger sind unveränderte Updates. Stabile Zustände: ${rows.filter(r=>r.stable).map(r=>sign(r.state)).join(', ')}.</p>`+String.raw`<p>Energiekontrolle: $\Delta E=-(s_i'-s_i)(\mathrm{net}_i-\theta_i)\le0$. Bei Gleichheit von Netzeingabe und Schwelle kann −1 zu +1 wechseln, ohne dass die Energie fällt. Die Konvergenz folgt zusätzlich daraus, dass auf einem Plateau nur die Anzahl der +1-Werte wachsen kann.</p>`,checks:['Alle acht Zustände und drei Nachfolger pro Zustand sind erfasst.','Nur ein Neuron pro Kante ändert seinen Wert.','Energie und Gleichheitsfälle sind überprüft.'],data:{weights,theta,rows}};break;
      }
      case 'backprop': {
        const x=integer(1,3),v=.5,w=1,eta=.1,target=integer(0,1),h=sigmoid(v*x),o=sigmoid(w*h),dOut=(target-o)*o*(1-o),dHidden=w*dOut*h*(1-h);
        q={title:'Backpropagation mit einem Hidden-Neuron',source:'Folien 174–183',prompt:String.raw`Netz: $x=${x}$ → Hidden-Neuron mit Gewicht $v=0.5$ → Ausgang mit Gewicht $w=1$. Beide Aktivierungen sind logistisch; beide Biaswerte sind anfangs 0 und werden mitgelernt. Ziel $t=${target}$, $\eta=0.1$, Fehler $E=(t-o)^2$, Update-Konvention $-\eta\nabla E/2$. Berechne Forward-Pass, Fehlerfaktoren und alle Parameter nach einem Schritt.`,fields:[field('Hidden-Ausgabe h',h),field('Ausgabe o',o),field('δ am Ausgang',dOut),field('Neues Gewicht v',v+eta*dHidden*x),field('Neues Gewicht w',w+eta*dOut*h)],hints:['h=σ(vx), o=σ(wh).','δ_out=(t−o)o(1−o), δ_hidden=w_alt δ_out h(1−h). Alle Deltas vor den Updates berechnen.'],solution:String.raw`<p>$h=${f(h)}$, $o=${f(o)}$; $\delta_o=${f(dOut)}$, $\delta_h=${f(dHidden)}$.</p><p>$w_{neu}=1+0.1\delta_o h=${f(w+eta*dOut*h)}$ und $v_{neu}=0.5+0.1\delta_h x=${f(v+eta*dHidden*x)}$.</p><p>Bias-Updates: $b_o^{neu}=0.1\delta_o=${f(eta*dOut)}$, $b_h^{neu}=0.1\delta_h=${f(eta*dHidden)}$. In der Schreibweise mit Schwellen gilt jeweils $\theta=-b$.</p><p>Für den Hidden-Fehler muss das <strong>alte</strong> Ausgangsgewicht benutzt werden. Sonst ist es nicht der Gradient des aktuellen Netzes.</p>`};break;
      }
      case 'cmeans': {
        const t=integer(-2,3),points=[[t,0],[t+2,0],[t+8,0],[t+10,0]],centers=[[t,0],[t+8,0]];
        q={title:'Ein c-Means-Schritt',source:'Folien 310–314',prompt:String.raw`Daten: ${points.map(vec).join(', ')}. Anfangszentren: ${centers.map(vec).join(' und ')}. Weise jeden Punkt dem nächsten Zentrum zu und berechne anschließend beide neuen Zentren gemeinsam. Verwende quadrierte euklidische Distanzen.`,fields:[field('Neues x von Zentrum 1',t+1),field('Neues x von Zentrum 2',t+9)],hints:['Die Zuordnung erfolgt vollständig mit den alten Zentren.','Ein neues Zentrum ist der Mittelwert seiner zugeordneten Punkte.'],solution:table(['Punkt','d₁²','d₂²','Cluster'],points.map(x=>[vec(x),dist2(x,centers[0]),dist2(x,centers[1]),dist2(x,centers[0])<dist2(x,centers[1])?1:2]))+`<p>Neue Zentren: ${vec([t+1,0])} und ${vec([t+9,0])}. Erst alle Zuordnungen festlegen, dann die Zentren aktualisieren. Das unterscheidet diesen Batch-Schritt vom Online-LVQ-Update.</p>`};break;
      }
      case 'cnn': {
        const c=integer(0,4),img=[[1+c,2+c,3+c],[4+c,5+c,6+c],[7+c,8+c,9+c]],kernel=[[1,0],[0,-1]],out=[[-4,-4],[-4,-4]];
        q={title:'CNN: Kernel anwenden und poolen',source:'Folien 263–266 · eigene Variante',prompt:String.raw`Bild $I=\begin{pmatrix}${img.map(r=>r.join('&')).join('\\\\')}\end{pmatrix}$, Kernel $K=\begin{pmatrix}1&0\\0&-1\end{pmatrix}$. Berechne die CNN-Kreuzkorrelation (Kernel nicht drehen), Stride 1, kein Padding. Danach ReLU und 2×2-Max-Pooling, Stride 2. Gib auch die Abmessungen an.`,fields:[field('Ausgabe oben links vor ReLU',-4),field('Zeilen der Feature Map',2,0),field('Gepoolter Wert nach ReLU',0)],hints:['Die Ausgabegröße pro Achse ist floor((N+2P−K)/S)+1.','Oben links: I₁₁ − I₂₂.'],solution:String.raw`<p>Größe: $(3-2)/1+1=2$, also 2×2. Jedes Fenster liefert −4; links oben $${img[0][0]}-${img[1][1]}=-4$.</p>$$S=\begin{pmatrix}-4&-4\\-4&-4\end{pmatrix},\quad\mathrm{ReLU}(S)=\begin{pmatrix}0&0\\0&0\end{pmatrix}.$$<p>Das 2×2-Max-Pooling ergibt eine 1×1-Ausgabe mit Wert 0. Bei mathematischer Faltung würde der Kernel um 180° gedreht; das ist hier ausdrücklich nicht die Konvention.</p>`};break;
      }
      default: throw new Error('Unbekannter Aufgabentyp: '+type);
    }
    return {...base,...q,id:`${type}-${seed}`};
  }
  const types=[['regression','Regressionsgerade'],['polynom','Polynomiale Regression'],['logit','Logit-Transformation'],['klassifikation','Logistische Entscheidung'],['bce','BCE & Lernschritt'],['softmax','Softmax'],['tlu','TLU-Polygon'],['rbf','RBF-Fläche'],['approximation','Funktionsapproximation'],['lvq','LVQ'],['som','SOM'],['hopfield','Hopfield'],['backprop','Backpropagation'],['cmeans','c-Means'],['cnn','CNN']];
  function grade(q,answers) { return q.fields.map((v,i)=> {const raw=String(answers[i]??'').trim().replace(',','.');const n=raw===''?NaN:Number(raw);return Number.isFinite(n)&&Math.abs(n-v.answer)<=v.tolerance;}); }
  return {make,types,grade,hopfield,sigmoid,format:f,table};
})();
if(typeof module!=='undefined'&&module.exports) module.exports=NNPractice;
