/* One continuous task view; all learning records stay local to this browser. */
(function(){
 'use strict';
 const C=NNCore,D=NNContent,M=NNMC,V=NNVisual,E=V.esc,KEY='ann_exam_focus_v1',OLD='ann_borgelt_state_v2',app=document.getElementById('app');
 const empty=()=>({version:1,current:'original-tlu',parts:{},drafts:{},history:[],mc:{},mcScope:'core',mcActive:null,mcBlock:null,paper:null});
 let s=empty(),storageOK=true,legacy=null;
 try {const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved?.version===1)s={...s,...saved};legacy=JSON.parse(localStorage.getItem(OLD)||'null');}catch{storageOK=false;}
 function save(){try{localStorage.setItem(KEY,JSON.stringify(s));}catch{storageOK=false;}const el=document.getElementById('storage-status');el.textContent=storageOK?'Dein Stand bleibt in diesem Browser.':'Speichern nicht verfügbar. Bitte exportiere deinen Stand vor dem Schließen.';}
 function math(el=app){if(window.renderMathInElement)window.renderMathInElement(el,{delimiters:[{left:'$$',right:'$$',display:true},{left:'$',right:'$',display:false}],throwOnError:false,strict:'ignore',trust:false});}
 const byId=id=>D.tasks.find(t=>t.id===id);
 const link=(task,part)=>`#/training/${task.id}/${part||s.parts[task.id]||task.parts[0].id}`;
 const title=t=>t.kind==='original'?'Aufgabe von 2024':t.kind==='transfer'?'Eigene Transferaufgabe':'Gezielter Rechenschritt';
 const completed=id=>s.history.some(h=>h.task===id);
 const draft=t=>s.drafts[t.id]||(s.drafts[t.id]={run:Date.now()+'-'+Math.random().toString(36).slice(2),parts:{},recorded:false});
 const partDraft=(t,p)=>draft(t).parts[p.id]||(draft(t).parts[p.id]={values:{},note:'',hints:0,recipe:false,revealed:false,helped:false,wrong:false,checks:{},details:{},rating:null});
 function header(eyebrow,h,intro=''){return `<div class="eyebrow">${eyebrow}</div><h1>${h}</h1>${intro?`<p class="intro">${intro}</p>`:''}`;}
 function overview(){const originals=D.tasks.filter(t=>t.kind==='original'),resume=byId(s.current)||originals[0],next=originals.find(t=>!completed(t.id))||C.nextTask(D.tasks,s.history,s.current);
  app.innerHTML=header('Aufgaben von 2024','Mit einer Aufgabe anfangen','Rechne selbst. Öffne genau die Hilfe, die du gerade brauchst. Danach festigst du das Verfahren mit einer veränderten Aufgabe.')+`<p class="theory-entry">Neu im Stoff? <a href="#/theorie">Mit den verständlichen Grundlagen beginnen →</a></p><div class="card"><div class="eyebrow">${Object.keys(s.drafts).length?'Weiterlernen':'Dein Einstieg'}</div><h2>${Object.keys(s.drafts).length?resume.title:next.title}</h2><p>${Object.keys(s.drafts).length?'Deine Rechenwerte und geöffneten Lösungen sind gespeichert.':'Beginne mit der Originalaufgabe. Du kannst jederzeit eine andere wählen.'}</p><a class="button primary" href="${link(Object.keys(s.drafts).length?resume:next)}">${Object.keys(s.drafts).length?'Fortsetzen':'Aufgabe öffnen'}</a></div><h2>Die fünf Aufgaben einmal bearbeiten</h2><ul class="task-list">${originals.map((t,i)=>{const done=Object.values(s.drafts[t.id]?.parts||{}).filter(p=>p.rating).length;return `<li><a class="task-row" href="${link(t)}"><div><strong>${i+1}. ${t.title}</strong><span class="small">${t.parts.length===1?'Eine vollständige Aufgabe':t.parts.length+' einzeln bearbeitbare Teile'}</span></div><span class="status ${completed(t.id)?'good':''}">${completed(t.id)?'Original bearbeitet':done?`${done}/${t.parts.length} Teile bearbeitet`:'Noch offen'}</span></a></li>`;}).join('')}</ul><p class="small">Bearbeitet ist noch nicht beherrscht. Eine neue Variante und eine spätere Wiederholung zeigen mehr als das Wiedererkennen der Originalzahlen.</p><h2>Mit Veränderungen festigen</h2><ul class="task-list">${D.tasks.filter(t=>t.kind==='transfer').map(t=>`<li><a class="task-row" href="${link(t)}"><div><strong>${t.title}</strong><span class="small">${t.purpose}</span></div><span class="status">${C.familyStatus(s.history,t.family)}</span></a></li>`).join('')}</ul><details><summary>Einen einzelnen Rechenschritt üben</summary><div class="recipe-grid">${D.tasks.filter(t=>t.kind==='repair').map(t=>`<a class="recipe-link" href="${link(t)}">${t.title}</a>`).join('')}</div></details><div class="split"><div class="card"><h3>Wahr oder falsch?</h3><p>Begriffe und typische Verwechslungen zu den Themen von 2024.</p><a class="button" href="#/mc">MC weiterüben</a></div><div class="card"><h3>Alles zusammen bearbeiten</h3><p>Fünf Rechenaufgaben und 30 Trainingsaussagen. Lösungen erst beim Vergleichen, ohne Pflichtuhr.</p><a class="button" href="#/gesamt">Gesamtdurchlauf öffnen</a></div></div><p class="small"><a href="#/quellen">Quellen, PDFs und Datenexport</a></p>`;
 }
 function statement(p){return `<div class="problem">${p.prompt}</div>${p.image?`<figure><img class="task-image" src="${p.image}" alt="Abbildung aus der Aufgabenübersicht 2024"><figcaption>Abbildung aus der bereitgestellten Vorlage.</figcaption></figure>`:''}${p.figure?(!p.image?p.figure:`<details><summary>Beschriftete Darstellung</summary>${p.figure}</details>`):''}${p.clarification?`<div class="clarification"><strong>Klarstellung für diese Bearbeitung</strong><br>${p.clarification}</div>`:''}`;}
 function taskView(t,p){s.current=t.id;s.parts[t.id]=p.id;const d=partDraft(t,p);save();
  app.innerHTML=`<div class="breadcrumb"><a href="#/">Alle Aufgaben</a> / ${title(t)}</div>`+header(title(t),t.title)+`<p class="source">${t.source}</p>${t.parts.length>1?`<nav class="parts" aria-label="Teilaufgaben">${t.parts.map(x=>`<a class="${x.id===p.id?'active':''}" href="${link(t,x.id)}">${x.title}${draft(t).parts[x.id]?.rating?' ✓':''}</a>`).join('')}</nav>`:''}`+`<article class="card" data-task="${t.id}" data-part="${p.id}">${statement(p)}${p.fields.length?`<details id="numbers" ${d.numbers?'open':''}><summary>Rechenwerte prüfen</summary><p class="small">Brüche und Dezimalkomma sind erlaubt. Vektoren mit Semikolon trennen, z. B. (1/2; −3). Die Kontrolle prüft diese Teilwerte; andere gültige Konstruktionen vergleichst du mit den Kriterien.</p><form id="answer-form"><div class="input-grid">${p.fields.map(q=>`<div><label for="answer-${q.id}">${q.label}</label><input type="text" autocomplete="off" id="answer-${q.id}" data-field="${q.id}" value="${E(d.values[q.id]||'')}" ${d.rating?'disabled':''}><div class="field-feedback" id="feedback-${q.id}"></div></div>`).join('')}</div><button type="submit" ${d.rating?'disabled':''}>Diese Werte prüfen</button><p id="number-result" role="status"></p></form></details>`:''}<div class="actions"><button id="recipe" aria-expanded="${d.recipe}">Rezept</button><button id="reveal" class="primary" aria-expanded="${d.revealed}">Lösung vergleichen</button><button id="next">Weiter →</button></div><div id="recipe-panel" ${d.recipe?'':'hidden'}>${p.recipes.map(D.recipeHTML).join('')}</div><section class="solution" id="solution-panel" ${d.revealed?'':'hidden'}>${NNExamSolutions.html(t,p,{expanded:d.explanation,extra:explorerHTML(p)})}<div class="rating"><h3>Deinen vollständigen Lösungsweg vergleichen</h3><p class="small">Die Bewertung der Zeichnung und des freien Rechenwegs ist deine Selbsteinschätzung.</p><div class="check-list">${p.checks.map((c,i)=>`<label><input type="checkbox" data-check="${i}" ${d.checks[i]?'checked':''}>${c}</label>`).join('')}</div><div class="actions"><button data-rating="independent" ${d.helped||d.wrong?'disabled':''}>Ohne Hilfe geschafft</button><button data-rating="helped">Mit Hilfe geschafft</button><button data-rating="again">Noch üben</button></div><p id="rating-note" class="small" role="status">${d.rating?ratingText(d.rating):d.helped||d.wrong?'Für diesen Versuch wurde Hilfe genutzt oder ein Rechenwert korrigiert. Selbstständig kannst du das Verfahren in einer neuen Bearbeitung prüfen.':'Für „Ohne Hilfe geschafft“ müssen alle Kriterien erfüllt sein.'}</p></div></section></article><details><summary>Diese Aufgabe erneut bearbeiten</summary><p>Startet einen frischen Versuch. Der bisherige Versuch bleibt im Verlauf erhalten.</p><button id="restart-task">Neuen Versuch starten</button></details><p class="small">${t.purpose} · <a href="#/quellen">Originalunterlagen</a></p>`;
  const draw=()=>{const y=scrollY;taskView(t,p);math();window.scrollTo(0,y);};
  document.getElementById('numbers')?.addEventListener('toggle',e=>{d.numbers=e.target.open;save();});
  app.querySelectorAll('[data-field]').forEach(input=>input.addEventListener('input',()=>{d.values[input.dataset.field]=input.value;if(d.revealed)d.helped=true;save();}));
  document.getElementById('answer-form')?.addEventListener('submit',e=>{e.preventDefault();const results=p.fields.map(q=>C.grade(q,d.values[q.id]));results.forEach((good,i)=>{const q=p.fields[i],el=document.getElementById('feedback-'+q.id);el.className='field-feedback '+(good?'correct':'incorrect');el.textContent=good?'Dieser Wert stimmt.':diagnose(t,p,q,d.values[q.id]);});if(results.some(x=>!x))d.wrong=true;d.firstCheck??=results;save();document.getElementById('number-result').textContent=results.every(Boolean)?'Diese Teilwerte stimmen. Prüfe auch die vollständige Konstruktion und Begründung.':`${results.filter(Boolean).length} von ${results.length} Teilwerten stimmen. Prüfe die markierten Stellen.`;if(d.wrong){app.querySelector('[data-rating="independent"]').disabled=true;document.getElementById('rating-note').textContent='Mindestens ein Rechenwert wurde korrigiert. Nutze später einen frischen Versuch für die selbstständige Kontrolle.';}});
  document.getElementById('recipe').onclick=()=>{d.recipe=!d.recipe;if(d.recipe)d.helped=true;save();draw();};
  document.getElementById('reveal').onclick=()=>{d.revealed=!d.revealed;save();draw();if(d.revealed)document.getElementById('solution-panel').scrollIntoView({block:'start'});};
  app.querySelectorAll('[data-check]').forEach(el=>el.onchange=()=>{d.checks[el.dataset.check]=el.checked;save();});
  app.querySelectorAll('[data-rating]').forEach(el=>el.onclick=()=>{const r=el.dataset.rating;if(r==='independent'&&(!p.checks.every((_,i)=>d.checks[i])||d.helped||d.wrong)){document.getElementById('rating-note').textContent='Prüfe zuerst alle Kriterien deiner vollständigen Lösung.';return;}d.rating=r;recordTask(t);save();draw();});
  document.getElementById('next').onclick=()=>{const i=t.parts.indexOf(p);if(i<t.parts.length-1)location.hash=link(t,t.parts[i+1].id);else location.hash=link(C.nextTask(D.tasks,s.history,t.id));};
  document.getElementById('restart-task').onclick=()=>{const old=draft(t);s.archivedDrafts??=[];s.archivedDrafts.push({task:t.id,...old});delete s.drafts[t.id];save();taskView(t,p);math();};
  app.querySelectorAll('.solution details:not([data-explanation])').forEach((el,i)=>{if(d.details[i])el.open=true;el.addEventListener('toggle',()=>{d.details[i]=el.open;save();});});
  document.querySelector('[data-explanation]')?.addEventListener('toggle',e=>{d.explanation=e.target.open;save();});
  wireGraphs();wireExplorer(p);Learn.enrichTask(t,p);app.querySelector('.task-theory-link a')?.addEventListener('click',()=>{if(!d.rating)d.helped=true;save();});math();
 }
 function ratingText(r){return r==='independent'?'Als selbstständig gelöst gespeichert.':r==='helped'?'Mit Hilfe bearbeitet. Eine passende Variante folgt später.':'Für eine gezielte Wiederholung vorgemerkt.';}
 function recordTask(t){const run=draft(t),ps=t.parts.map(p=>run.parts[p.id]);if(!ps.every(p=>p?.rating))return;const helped=ps.some(p=>p.helped||p.wrong||p.rating!=='independent'),rating=ps.some(p=>p.rating==='again')?'again':helped?'helped':'independent',h={task:t.id,family:t.family,kind:t.kind,rating,helped,at:Date.now(),run:run.run,seq:s.history.length};const prev=s.history.findIndex(x=>x.run===run.run);if(prev>=0)s.history[prev]={...h,at:s.history[prev].at,seq:s.history[prev].seq};else s.history.push(h);run.recorded=true;}
 function diagnose(t,p,q,input){const n=C.number(input);if(!String(input||'').trim())return 'Noch kein Wert eingetragen.';if(t.family==='approx'&&q.id==='delta'&&p.model&&n===C.approximation(p.model.coeff,p.model.start,p.model.end,p.model.step).ys[1])return 'Du hast die Höhe eingesetzt. Das Gewicht ist die Änderung zur vorherigen Höhe.';if(t.family==='hopfield'&&q.vector){const a=C.numbers(input);if(a.length===3&&q.id==='next'&&(a[0]!==-1||a[2]!==-1))return 'Hier wird nur u₂ aktualisiert. Das erste und dritte Zeichen bleiben −1.';}if(q.vector&&C.numbers(input).some(x=>x===null))return 'Vektoren als Zahlen mit Semikolon eingeben, z. B. (1/2; −3).';if(!q.vector&&n===null)return 'Eine Zahl oder einen Bruch eingeben, z. B. −3/2.';return 'Dieser Teilwert stimmt noch nicht. Vergleiche Ansatz, Vorzeichen und eingesetzte Werte.';}
 function explorerHTML(p){if(!p.model?.params&&!p.model?.centers&&!p.model?.coeff)return '';return `<details class="explorer"><summary>Mit einem eigenen Punkt kontrollieren</summary><p>Setze Zahlen ein und verfolge die tatsächliche Netz-Ausgabe.</p><div class="actions"><label>x${p.model.coeff?'':'₁'} <input id="explore-x" type="number" step="any" value="${p.model.coeff?p.model.start:2}"></label>${p.model.coeff?'':'<label>x₂ <input id="explore-y" type="number" step="any" value="2"></label>'}<button id="explore-check">Punkt einsetzen</button></div><p id="explore-result" role="status"></p></details>`;}
 function wireExplorer(p){const btn=document.getElementById('explore-check');if(!btn)return;btn.onclick=()=>{const x=Number(document.getElementById('explore-x').value),y=Number(document.getElementById('explore-y')?.value);let text='';if(p.model.params){const tests=p.model.params.map(([a,b,t])=>a*x+b*y>=t?1:0),sum=tests.reduce((a,h,i)=>a+h*[2,2,1,1][i],0);text=`h = ${C.vec(tests)}. Gewichtete Summe = ${C.fmt(sum)}. Vergleich mit 5 → Ausgabe ${sum>=5?1:0}.`;}else if(p.model.centers){const {centers,r}=p.model,ds=centers.map((c,i)=>i?Math.max(Math.abs(x-c[0]),Math.abs(y-c[1])):Math.abs(x-c[0])+Math.abs(y-c[1])),hs=ds.map((d,i)=>d<=(i?r/2:r)?1:0);text=`Abstände: ${C.vec(ds)}. Aktivierungen: ${C.vec(hs)}. Ausgabe: ${hs[0]-hs[1]-hs[2]}. Ränder sind in dieser Aufgabe egal.`;}else{const m=p.model,a=C.approximation(m.coeff,m.start,m.end,m.step);text=x<m.start||x>m.end?`Wähle x zwischen ${m.start} und ${m.end}.`:`f(x) = ${C.fmt(a.f(x))}; MLP = ${C.fmt(a.mlp(x))}; RBF = ${C.fmt(a.rbf(x))}.`;}document.getElementById('explore-result').textContent=text;};}
 function wireGraphs(){app.querySelectorAll('[data-hop-focus]').forEach(sel=>sel.onchange=()=>{const fig=sel.closest('figure');fig.classList.toggle('focused',sel.value!=='all');fig.querySelectorAll('[data-edge-source]').forEach(g=>g.classList.toggle('selected',g.dataset.edgeSource===sel.value));});}
 function recipes(id){const r=D.recipes[id];app.innerHTML=header('Zum Nachschlagen',r?r.title:'Sieben Rechenrezepte','Öffne das Rezept, das zu deiner aktuellen Aufgabe passt.')+(r?`<a href="#/rezepte">← Alle Rezepte</a><article class="card">${D.recipeHTML(id)}</article><a class="button primary" href="${link(D.tasks.find(t=>t.kind==='original'&&t.parts.some(p=>p.recipes.includes(id))),D.tasks.find(t=>t.kind==='original'&&t.parts.some(p=>p.recipes.includes(id))).parts.find(p=>p.recipes.includes(id)).id)}">An der Originalaufgabe anwenden</a>`:`<div class="recipe-grid">${Object.entries(D.recipes).map(([id,r])=>`<a class="recipe-link" href="#/rezepte/${id}"><strong>${r.title}</strong><br><span class="small">${r.source}</span></a>`).join('')}</div><div class="actions"><a class="button" href="materials/rechenrezepte.pdf" target="_blank" rel="noopener">Rechenguide als PDF</a><a class="button" href="materials/ausarbeitung-2024.pdf" target="_blank" rel="noopener">Ausführliche Ausarbeitung</a></div><details><summary>Weitere Folienthemen bei Bedarf nachschlagen</summary><p class="small">Diese Themen sind in den Folien enthalten. Sie bilden keinen vorgeschalteten Pflichtlernweg.</p>${NNReference.map(m=>`<p><a href="#/nachschlagen/${m.id}">${m.title}</a> · ${m.source}</p>`).join('')}</details>`);}
 function sources(){const notes=legacy?.notes||{};app.innerHTML=header('Quellen & eigene Daten','Unterlagen und Lernstand')+`<div class="card"><h2>Die Grundlage</h2><p>Aufgabenübersicht vom 10. Juli 2024 und der bereitgestellte Foliensatz von Christian Borgelt (512 Folien). Die Übersicht enthält sieben ausformulierte MC-Aussagen und 13 Stichworte. Die sieben Originalaussagen stehen unverändert auf Englisch im Fragenbestand. Die anderen MC-Formulierungen sind rekonstruierte oder eigene Trainingsfragen.</p><div class="actions"><a class="button" href="materials/aufgaben-2024.pdf" target="_blank" rel="noopener">Vorlage 2024</a><a class="button" href="materials/ausarbeitung-2024.pdf" target="_blank" rel="noopener">Eigene Ausarbeitung</a><a class="button" href="materials/rechenrezepte.pdf" target="_blank" rel="noopener">Rechenguide</a><a class="button" href="https://borgelt.net/slides/nn.pdf" target="_blank" rel="noopener">Folien beim Autor</a></div><p class="small">Foliennummern beziehen sich auf deine bereitgestellte Datei nn(1).pdf. Die öffentliche Fassung beim Autor kann anders nummeriert sein. Die Ausarbeitung ist keine offizielle Musterlösung.</p><h3>Prüfungsformat</h3><p>Folie 2: fünf numerische/grafische Aufgaben mit zusammen ungefähr 70 Punkten; sechs MC-Blöcke mit je fünf Aussagen, zusammen 30 Punkte. Die Punkte einzelner Rechenaufgaben und die aktuelle Bestehensgrenze sind nicht belegt. Der Lernstand enthält deshalb keine Notenprognose.</p><h3>Geklärte Konventionen</h3><p>Eingabeschicht mitzählen (Folie 80). LVQ-Gewinnerregel und Zweiprototypen-Regel getrennt behandeln. SOM-Gitterlesart offenlegen. RBF-Randüberlappungen kontrollieren. Hopfield-Gleichheitsfälle nach der angegebenen Schwellenregel auswerten.</p></div><div class="card"><h2>Deinen Stand sichern</h2><p>Der neue Lernstand und vorhandene alte Daten werden gemeinsam exportiert. Die alte Speicherung wird durch den Umbau nicht überschrieben.</p><div class="actions"><button id="export">Stand exportieren</button><label class="button">Stand importieren <input id="import" type="file" accept="application/json,.json"></label></div><p id="data-message" role="status"></p><details><summary>Frühere Notizen und Bewertungen (${Object.keys(notes).length} Notizen)</summary><p class="small">Alte Häkchen werden nicht in neue Kompetenznachweise umgedeutet. Der komplette Altstand ist im Export enthalten.</p>${Object.entries(notes).map(([k,n])=>`<h3>${E(k)}</h3><div class="archive-note">${E(n)}</div>`).join('')}<pre class="archive-note">${E(JSON.stringify({known:legacy?.known||{},done:legacy?.done||{},scores:legacy?.scores||{},exam:legacy?.exam||null},null,2))}</pre></details><details><summary>Bisherige neue Versuche (${s.history.length})</summary>${s.history.map(h=>`<p>${E(byId(h.task)?.title||h.task)} · ${ratingText(h.rating)} · ${new Date(h.at).toLocaleDateString('de-DE')}</p>`).join('')||'<p>Noch keine vollständig bewertete Aufgabe.</p>'}</details></div>`;
  const snapshot=()=>({schema:'nn-focus-v1',exported:new Date().toISOString(),state:s,legacy,originalLegacy:JSON.parse(localStorage.getItem(OLD)||'null')});
  const download=(data,name)=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
  document.getElementById('export').onclick=()=>download(snapshot(),'nn-lernstand.json');
  const backupButton=document.createElement('button');backupButton.id='export-backup';backupButton.textContent='Stand vor dem letzten Import sichern';document.getElementById('export').parentElement.append(backupButton);
  backupButton.onclick=()=>{const data=localStorage.getItem('ann_focus_before_import');if(data)download(JSON.parse(data),'nn-stand-vor-import.json');else document.getElementById('data-message').textContent='Noch kein Import durchgeführt.';};
  document.getElementById('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());let next=s,old=legacy;if(data?.schema==='nn-focus-v1'&&validState(data.state)){next={...empty(),...data.state};if(data.legacy&&typeof data.legacy==='object'&&!Array.isArray(data.legacy))old=data.legacy;}else if(data&&!data.schema&&typeof data==='object'&&(data.notes||data.known||data.state?.notes)){old=data.state||data;}else throw Error('Die Datei enthält keinen gültigen NN-Lernstand.');const backup=JSON.stringify(snapshot());localStorage.setItem('ann_focus_before_import',backup);localStorage.setItem(KEY,JSON.stringify(next));if(old)localStorage.setItem('ann_focus_imported_legacy',JSON.stringify(old));s=next;legacy=old;save();document.getElementById('data-message').textContent='Importiert. Der Stand vor dem Import ist gesichert; ursprüngliche Altdaten bleiben erhalten.';}catch(err){document.getElementById('data-message').textContent='Import nicht durchgeführt: '+err.message;}};
 }
 function validState(x){
  const object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),map=(v,test)=>object(v)&&Object.values(v).every(test),str=v=>typeof v==='string',bool=v=>typeof v==='boolean',nat=v=>Number.isInteger(v)&&v>=0,answer=v=>v===null||['true','false','skip'].includes(v);
  const part=p=>object(p)&&map(p.values,str)&&str(p.note)&&nat(p.hints)&&['recipe','revealed','helped','wrong'].every(k=>bool(p[k]))&&map(p.checks,bool)&&map(p.details,bool)&&(p.explanation===undefined||bool(p.explanation))&&(p.rating===null||['independent','helped','again'].includes(p.rating));
  const block=b=>b===null||(object(b)&&Array.isArray(b.groups)&&b.groups.length>0&&b.groups.every(g=>M.groups.some(([id])=>id===g))&&nat(b.turn)&&map(b.answers,answer)&&bool(b.finished));
  const paper=p=>p===null||(object(p)&&['original','transfer'].includes(p.kind)&&map(p.notes,str)&&map(p.answers,answer)&&bool(p.finished)&&nat(p.turn));
  return NNLearn.valid(x?.learning)&&object(x)&&x.version===1&&str(x.current)&&map(x.parts,str)&&map(x.drafts,d=>object(d)&&str(d.run)&&map(d.parts,part))&&Array.isArray(x.history)&&x.history.every(h=>object(h)&&str(h.task)&&str(h.family)&&['original','transfer','repair'].includes(h.kind)&&['independent','helped','again'].includes(h.rating)&&bool(h.helped)&&Number.isFinite(h.at)&&nat(h.seq))&&map(x.mc,m=>object(m)&&nat(m.count)&&bool(m.lastCorrect)&&Number.isFinite(m.at)&&nat(m.seq))&&['core','original','extra','variants',...M.groups.map(g=>g[0])].includes(x.mcScope)&&(x.mcActive===null||(object(x.mcActive)&&M.concepts.some(c=>c.id===x.mcActive.concept)&&(nat(x.mcActive.form)||(x.mcActive.form==='original'&&M.concepts.some(c=>c.id===x.mcActive.concept&&c.original)))&&answer(x.mcActive.answer)))&&block(x.mcBlock)&&(x.mcBlockHistory===undefined||(Array.isArray(x.mcBlockHistory)&&x.mcBlockHistory.every(b=>b!==null&&block(b))))&&paper(x.paper)&&(x.archivedDrafts===undefined||Array.isArray(x.archivedDrafts))&&(x.paperHistory===undefined||Array.isArray(x.paperHistory));
 }
 function reference(id){const m=NNReference.find(m=>m.id===id)||NNReference[0];app.innerHTML=`<div class="breadcrumb"><a href="#/rezepte">Rechenrezepte</a> / Nachschlagen</div>`+header('Weitere Folien',m.title,'Bei Bedarf nachlesen. Diese Inhalte sind kein vorgeschalteter Pflichtlernweg.')+m.sections.map(sec=>`<details class="card reference"><summary>${sec.title}</summary>${sec.html}<p class="source">${sec.source||m.source}</p></details>`).join('');app.querySelectorAll('.practice-card:empty,[id$="-lab"]').forEach(e=>e.remove());}
 function blockData(groups,turn=0){return groups.map(id=>({id,title:M.groups.find(g=>g[0]===id)[1],questions:M.concepts.filter(c=>c.group===id).map(c=>M.question(c,turn))}));}
 function blocksHTML(groups,answers,reveal){return groups.map(g=>`<section class="card"><h2>${g.title}</h2><p>${NNQuestions.get('block-'+g.id+'-0').stem}</p>${g.questions.map((q,i)=>`<fieldset class="block-question"><legend>${i+1}. ${q.text}</legend><div class="radios">${[['true','Wahr'],['false','Falsch'],['skip','Auslassen']].map(([val,label])=>`<label><input type="radio" name="${q.id}" data-block="${q.id}" value="${val}" ${(answers[q.id]||'skip')===val?'checked':''} ${reveal?'disabled':''}>${label}</label>`).join('')}</div>${reveal?`<div class="feedback"><strong>${q.correct?'Wahr':'Falsch'}.</strong> ${q.explanation}${!q.correct?`<p><strong>Richtig lautet es:</strong> ${NNQuestions.get(q.id).correction}</p>`:''}<p class="source">${q.source} · <a data-learning-theory href="#/theorie/${NNQuestions.get(q.id).topic}">Grundlage nachlesen</a></p></div>`:''}</fieldset>`).join('')}${reveal?`<p><strong>${C.scoreBlock(g.questions,answers)} / 5 Punkte</strong></p>`:''}</section>`).join('');}
 function recordMC(groups,answers){for(const q of groups.flatMap(g=>g.questions)){const m=s.mc[q.concept]||{count:0},seq=Object.values(s.mc).reduce((n,m)=>n+(m.count||0),0);s.mc[q.concept]={...m,count:m.count+1,lastCorrect:['true','false'].includes(answers[q.id])&&(answers[q.id]==='true')===q.correct,at:Date.now(),seq};}}
 function paperView(){if(!s.paper){app.innerHTML=header('Alles zusammen','Ein vollständiger Durchlauf','Fünf Rechenaufgaben und 30 MC-Trainingsaussagen. Du kannst jederzeit unterbrechen und später fortsetzen. Lösungen erscheinen erst beim Vergleichen.')+`<div class="actions"><button data-paper="original" class="primary">Mit den Aufgaben von 2024</button><button data-paper="transfer">Mit den Transferaufgaben</button></div><p class="small">Die MC-Fragen sind eigene oder rekonstruierte Aussagen. Für freie Rechnungen gibt es keine erfundene automatische Punktevergabe.</p>`;app.querySelectorAll('[data-paper]').forEach(b=>b.onclick=()=>{s.paper={kind:b.dataset.paper,notes:{},answers:{},finished:false,turn:b.dataset.paper==='original'?0:1};save();paperView();math();});return;}
  const p=s.paper,tasks=D.tasks.filter(t=>t.kind===p.kind),groups=blockData(M.groups.map(g=>g[0]),p.turn);app.innerHTML=header('Gesamtdurchlauf',p.kind==='original'?'Die Aufgaben von 2024':'Fünf Transferaufgaben',p.finished?'Vergleiche auch Zeichnungen, Parameter und Begründungen.':'Rechne auf Papier. Du kannst die Seite jederzeit verlassen; der Stand bleibt erhalten.')+tasks.map((t,i)=>`<article class="paper-task"><h2>${i+1}. ${t.title}</h2>${t.parts.map(part=>`<h3>${part.title}</h3>${statement(part)}`).join('')}${p.finished?`<details class="paper-solution"><summary>Vollständige Lösung und Kriterien</summary>${t.parts.map(part=>`<h3>${part.title}</h3>${NNExamSolutions.html(t,part)}<ul>${part.checks.map(c=>`<li>${c}</li>`).join('')}</ul>`).join('')}</details>`:''}</article>`).join('')+`<h2>6. Multiple Choice</h2><p class="small">Eigene Trainingsformulierungen zu den sechs Themenblöcken von 2024.</p>`+blocksHTML(groups,p.answers,p.finished)+(p.finished?`<div class="feedback">MC: <strong>${groups.reduce((n,g)=>n+C.scoreBlock(g.questions,p.answers),0)} / 30 Punkte</strong><p>Rechenaufgaben anhand der vollständigen Kriterien selbst vergleichen. Daraus wird keine Note abgeleitet.</p></div><button id="paper-new">Neuen Gesamtdurchlauf vorbereiten</button>`:'<button id="paper-finish" class="primary">Abgeben und Lösungen vergleichen</button>');
  app.querySelectorAll('[data-block]').forEach(el=>el.onchange=()=>{p.answers[el.dataset.block]=el.value;save();});document.getElementById('paper-finish')?.addEventListener('click',()=>{p.finished=true;recordMC(groups,p.answers);save();paperView();math();});document.getElementById('paper-new')?.addEventListener('click',()=>{s.paperHistory??=[];s.paperHistory.push(s.paper);s.paper=null;save();paperView();});wireGraphs();
 }
 const Learn=NNLearn.create({app,save,math,E,header,state:()=>s});
 const aliases={klausur:'',aufgaben:'',abfragen:'mc',task6:'mc',cheatsheet:'rezepte',task1:'training/original-tlu',task2:'training/original-rbf',task3:'training/original-approx',task4:'training/original-learning',task5:'training/original-hopfield',regression:'nachschlagen/regression',klassifikation:'nachschlagen/klassifikation',modellwahl:'nachschlagen/modellwahl',deeplearning:'nachschlagen/theorie'};
 function route(){
  Learn.beforeRoute();let path=decodeURIComponent(location.hash.replace(/^#\/?/,'')),bits=path.split('/');
  if(Object.hasOwn(aliases,bits[0])){location.replace('#/'+aliases[bits[0]]);return;}
  const page=bits[0];document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===(page==='theorie'?'theorie':['mc','fragen'].includes(page)?'mc':['rezepte','nachschlagen','quellen'].includes(page)?'rezepte':'training')));
  if(page==='training'){const t=byId(bits[1]);if(t){const p=t.parts.find(p=>p.id===bits[2])||t.parts.find(p=>p.id===s.parts[t.id])||t.parts[0];taskView(t,p);}else overview();}
  else if(page==='mc'){Learn.training(bits);}
  else if(page==='fragen')Learn.catalog(bits);
  else if(page==='theorie')Learn.theory(bits);
  else if(page==='rezepte')recipes(bits[1]);else if(page==='quellen')sources();else if(page==='nachschlagen')reference(bits[1]);else if(page==='gesamt')paperView();else overview();
  math();if(page!=='theorie')window.scrollTo(0,0);Learn.restoreReturn();document.title='NN · '+(app.querySelector('h1')?.textContent||'Klausur lernen');
 }

 try{const imported=JSON.parse(localStorage.getItem('ann_focus_imported_legacy')||'null');if(imported)legacy=imported;}catch{}
 window.addEventListener('hashchange',route);route();save();
})();
