(function(root){
 'use strict';
 const C=NNCore,V=NNVisual,T=String.raw,f=C.fmt,v=C.vec;
 const W=root.NNWorkedSolutions||(typeof require==='function'?require('./study-worked-solutions.js'):null);
 const table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 const detail=(title,body)=>`<details class="calculation"><summary>${title}</summary>${body}</details>`;
 const field=(id,label,answer,extra={})=>({id,label,answer,...extra});
 const recipes={
  tlu:{title:'TLU: Randtests und Ausgang',source:'Folien 17–35, 80',steps:[
   T`<strong>Randgeraden bestimmen.</strong> Durch $P=(p_1,p_2)$ und $Q=(q_1,q_2)$: $m=(q_2-p_2)/(q_1-p_1)$ und $x_2=p_2+m(x_1-p_1)$. Bei einer senkrechten Kante direkt $x_1=p_1$ verwenden.`,
   T`<strong>Seite wählen.</strong> Setze einen gewünschten Innenpunkt ein. Forme den passenden Test zu $w_1x_1+w_2x_2\ge\theta$ um. Bei Multiplikation mit $-1$ dreht sich das Ungleichheitszeichen um.`,
   T`<strong>Parameter ablesen.</strong> Die Zahlen vor $x_1,x_2$ sind die Gewichte, rechts steht die Schwelle. Der Test liefert $h_i=1$, wenn er erfüllt ist, sonst $0$.`,
   T`<strong>Tests verbinden.</strong> Für die hier gezeigten eingedellten Flächen: $h_1\land h_2\land(h_3\lor h_4)$. Das ergibt Ausgangsgewichte $(2,2,1,1)$ und Schwelle $5$. Bei anderen Flächen die passende UND-/ODER-Verknüpfung aus der Zeichnung bestimmen.`,
   T`<strong>Netz angeben.</strong> Eingabe → Randtests → Ausgang sind drei Schichten. Schreibe alle Gewichte, Schwellen und Verbindungen auf; prüfe einen Innen- und einen Außenpunkt.`
  ]},
  rbf:{title:'RBF-Fläche: Bausteine addieren und abziehen',source:'Folien 288–291',steps:[
   T`<strong>Fläche zerlegen.</strong> $L_1$ ergibt eine Raute, $L_2$ einen Kreis, $L_\infty$ ein Quadrat. Hier: eine Grundraute und zwei Abzugsquadrate.`,
   T`<strong>Zentrum und Radius ablesen.</strong> Zentrum = Mittelpunkt. Quadrat-Radius = halbe Seitenlänge; Raute-Radius = Abstand vom Mittelpunkt zu einer Spitze.`,
   T`<strong>Neuron definieren.</strong> Berechne $d_1=|x_1-c_1|+|x_2-c_2|$ bzw. $d_\infty=\max(|x_1-c_1|,|x_2-c_2|)$. Setze $h_i=1$ bei $d_i\le\sigma_i$, sonst $0$.`,
   T`<strong>Ausgabe aufstellen.</strong> Grundfläche mit $+1$, Abzüge mit $-1$ gewichten: hier $y=h_1-h_2-h_3$, linearer Ausgang, Schwelle $0$.`,
   T`<strong>Prüfen.</strong> Gewünschtes Inneres: $y=1$. Ausgesparte Teile und außen: $y\le0$. Alle Zentren, Distanzen, Radien, Aktivierungen und Ausgabegewichte angeben.`
  ]},
  mlp:{title:'MLP-Näherung: Höhen durch Sprünge erreichen',source:'Folien 80, 99–104',steps:[
   T`<strong>Stützstellen wählen.</strong> Für die Aufgaben hier passen $1+8+1=10$ Neuronen. Teile $[a,b]$ in acht Abschnitte: $h=(b-a)/8$, $x_i=a+ih$ für $i=0,\ldots,8$.`,
   T`<strong>Wertetabelle rechnen.</strong> Berechne $y_i=f(x_i)$ und ab $i=1$ die Sprünge $\Delta y_i=y_i-y_{i-1}$.`,
   T`<strong>Hidden-Neuronen festlegen.</strong> Für jeden Sprung: Eingangsgewicht $1$, Schwelle $x_i$, Aktivierung $h_i(x)=1$ bei $x\ge x_i$, sonst $0$.`,
   T`<strong>Linearer Ausgang.</strong> $\widehat f(x)=y_0+\sum_{i=1}^8\Delta y_i h_i(x)$. Gewichte = Sprünge, Ausgangsschwelle $-y_0$ bei $out=net-\theta$.`,
   T`<strong>Zeichnen und zählen.</strong> Auf jedem $[x_i,x_{i+1})$ Höhe $y_i$ zeichnen. An $x_8$ gilt $y_8$. Neuronenzahl und alle Parameter angeben.`
  ]},
  approx:{title:'RBF-Näherung: Stützwerte linear verbinden',source:'Folien 291–298',steps:[
   T`<strong>Zentren wählen.</strong> Neun Zentren ergeben mit Ein- und Ausgang $11$ Neuronen. Setze $c_i=a+ih$, $h=(b-a)/8$, $i=0,\ldots,8$.`,
   T`<strong>Höhen berechnen.</strong> Ausgabegewicht $w_i=f(c_i)$ für jedes Zentrum.`,
   T`<strong>Basisfunktionen aufstellen.</strong> Abstand $d_i=|x-c_i|$, Radius $h$, Dreiecksaktivierung $h_i(x)=\max(0,1-d_i/h)$.`,
   T`<strong>Ausgabe bilden.</strong> $\widehat f(x)=\sum_i w_i h_i(x)$; linearer Ausgang mit Schwelle $0$.`,
   T`<strong>Zeichnen und kontrollieren.</strong> Verbinde die Punkte $(c_i,f(c_i))$ durch Geraden. An einem Zentrum stimmt der Funktionswert; in der Mitte zweier Zentren ist die Ausgabe der Mittelwert ihrer Höhen.`
  ]},
  lvq:{title:'LVQ: Winner bestimmen und Vektoren ändern',source:'Folien 336, 340',steps:[
   T`<strong>Start notieren.</strong> Prototypen, Klassen, Lernrate $\eta$ und Datenreihenfolge. Für einen getrennten Durchlauf wieder mit den ursprünglichen Vektoren beginnen.`,
   T`<strong>Abstände vergleichen.</strong> Für den aktuellen Datenpunkt $x$: $d_k^2=\sum_j(x_j-r_{kj})^2$. Kleinster Wert = Winner.`,
   T`<strong>Regel auswählen.</strong> Ohne Klassen: Winner anziehen. Gewinnerregel mit Klassen: Winner bei passender Klasse anziehen, sonst abstoßen. Nur wenn die Zweiprototypen-Regel verlangt ist: die zwei nächsten verschieden klassifizierten Prototypen gemeinsam behandeln, sofern einer zur Datenklasse passt.`,
   T`<strong>Update rechnen.</strong> Anziehen: $r'=r+\eta(x-r)$. Abstoßen: $r'=r-\eta(x-r)$. Andere Prototypen bleiben gleich.`,
   T`<strong>Weiterrechnen.</strong> Beim nächsten Datenpunkt mit den neuen Vektoren erneut Abstände bestimmen. Am Ende: Endvektoren und Gesamtänderungen $r_{Ende}-r_{Start}$ angeben.`
  ]},
  som:{title:'SOM: Winner, Nachbarschaft, Update',source:'Folien 364–367',steps:[
   T`<strong>Winner finden.</strong> Vergleiche $\|x-r\|^2$ für die alten Prototypen. Notiere den Gitterindex $(i_*,j_*)$ des nächsten Prototyps.`,
   T`<strong>Gitterabstand berechnen.</strong> Für jedes Neuron $(i,j)$: $d_G^2=(i-i_*)^2+(j-j_*)^2$. Verwende die Gitterindizes, nicht die Datenraumkoordinaten.`,
   T`<strong>Nachbarschaft einsetzen.</strong> $h_{ij}=e^{-d_G^2/(2\sigma^2)}$, effektive Lernrate $\alpha_{ij}=\eta h_{ij}$. Beim Winner ist $h=1$.`,
   T`<strong>Alle Änderungen rechnen.</strong> $\Delta r_{ij}=\alpha_{ij}(x-r_{ij})$, dann $r_{ij}^{neu}=r_{ij}+\Delta r_{ij}$. Innerhalb dieses Schritts überall dieselben alten Vektoren verwenden.`
  ]},
  hopfield:{title:'Hopfield: Zustandstabelle und Graph',source:'Folien 380–390',steps:[
   T`<strong>Alle Zustände aufschreiben.</strong> Bei drei bipolaren Neuronen gibt es $2^3=8$ Zustände in der Reihenfolge $(s_1,s_2,s_3)$.`,
   T`<strong>Netzeingaben berechnen.</strong> Pro Zustand und Neuron: $net_i=\sum_{j\ne i}w_{ij}s_j$.`,
   T`<strong>Einzelupdates bilden.</strong> Bei $net_i\ge\theta_i$ setze nur $s_i$ auf $+1$, sonst auf $-1$. Für jedes der drei Updates erneut vom ursprünglichen Zeilenzustand ausgehen.`,
   T`<strong>Graph zeichnen.</strong> Jede Nachfolgerzelle wird ein Pfeil mit Neuronennummer. Selbstnachfolger als Schleifen zeichnen oder ausdrücklich in der Tabelle angeben.`,
   T`<strong>Vollständigkeit prüfen.</strong> Acht Zustände mal drei Updates = $24$ Nachfolger. Ein Zustand ist stabil, wenn alle drei Updates ihn unverändert lassen.`
  ]}
 };
 function recipeHTML(id){const r=recipes[id];return `<h3>${r.title}</h3><ol class="steps">${r.steps.map(s=>`<li>${s}</li>`).join('')}</ol><p class="source">${r.source}</p>`;}


 function tlu(kind){const original=kind==='original',points=original?[[1,4],[4,4],[3,1],[3,3]]:[[5,5],[2,5],[3,2],[3,4]],params=original?[[0,-1,-4],[-3,1,-8],[1,0,3],[1,2,9]]:[[0,-1,-5],[3,1,11],[-1,0,-3],[-1,2,5]],tests=original?[[2,3.8],[3.2,2],[2,2],[4,2],[2,5]]:[[4,4.8],[2.8,3],[4,3],[2,3],[4,6]];
  const diagram=V.plane({polygons:[points],points:points.map(([x,y],i)=>({x,y,label:'ABCD'[i]})),range:[0,6,0,7],title:'Polygon mit beschrifteten Eckpunkten'});
  return {id:`${kind}-tlu`,family:'tlu',kind,title:'TLU: die Fläche als Netz',purpose:original?'Aufgabe 1 · Zahlen und Form der Vorlage':'Gespiegelte und verschobene Form; Seiten und Gewichte selbst bestimmen',source:'2024, Aufgabe 1 · Folien 17–35, 80',parts:[{id:'netz',title:'Netz konstruieren',recipes:['tlu'],prompt:T`Konstruiere ein dreischichtiges Perzeptron, das innerhalb der gezeigten Fläche $+1$ und außerhalb $0$ liefert. Gib alle Gewichte, Schwellen und Verbindungen an.`,clarification:T`Konvention nach Folie 80: Die Eingabeschicht zählt mit. Randpunkte zählen hier zur Fläche. ${original?'Die Koordinaten sind aus der Vorlage abgelesen.':'Eigene Transferaufgabe; die Zeichnung ist die Vorgabe.'}`,image:original?'exam_task_img_19.png':null,figure:diagram,fields:params.map((p,i)=>field(`h${i+1}`,`Kante ${['AB','BC','CD','DA'][i]}: (w₁; w₂; θ) für die Innenseite`,p,{vector:true,scale:true})),solution:'',checks:['Randgeraden und gewünschte Seiten stimmen.','Netz hat drei Schichten einschließlich Eingabe.','Ausgabegewichte und Schwelle erfüllen die ganze logische Bedingung.','Alle Parameter und Verbindungen sind angegeben.'],model:{points,params,tests}}]};
 }

 function rbf(kind){const o=kind==='original',c=o?[2,2]:[1,2],r=o?1:2,sgn=o?1:-1,centers=[c,[c[0]-sgn*r/2,c[1]+r/2],[c[0]+sgn*r/2,c[1]-r/2]],polys=[[c,[c[0]+sgn*r,c[1]],[c[0],c[1]+r]],[c,[c[0]-sgn*r,c[1]],[c[0],c[1]-r]]],range=[c[0]-r-1,c[0]+r+1,c[1]-r-1,c[1]+r+1];
  return {id:`${kind}-rbf`,family:'rbf',kind,title:'RBF: eine Fläche zusammensetzen',purpose:o?'Aufgabe 2 · Form und Zahlen der Vorlage':'Andere Diagonale, anderer Mittelpunkt und Radius',source:'2024, Aufgabe 2 · Folien 288–291',parts:[{id:'flaeche',title:'Netz konstruieren',recipes:['rbf'],prompt:T`Konstruiere ein RBF-Netzwerk mit Ausgabe $1$ innerhalb der schattierten Fläche und $\le0$ außerhalb. Ränder sind egal. Die Distanzfunktionen dürfen je Knoten verschieden sein, müssen aber zur Minkowski-Familie gehören. Gib Zentren, Distanzen, Netzeingaben, Aktivierungen und Gewichte vollständig an.`,image:o?'exam_task_img_20.png':null,figure:V.plane({polygons:polys,range,title:'Die zwei gewünschten Dreiecke'}),clarification:o?'Zentren und Koordinaten werden aus der Abbildung abgelesen.':'Eigene Transferaufgabe. Wähle die Bausteine selbst.',fields:[field('radius','Radius der Grundraute',r),field('square','Radius eines Abzugsquadrats',r/2),field('upper','Zentrum des oberen Abzugsquadrats',centers[1],{vector:true}),field('lower','Zentrum des unteren Abzugsquadrats',centers[2],{vector:true})],solution:'',checks:['Zentren, Metriken und Radien angegeben.','Hidden-Aktivierungen und linearer Ausgang vollständig definiert.','Gewünschtes Inneres, Abzüge und Außenbereich begründet.'],model:{centers,r,sgn,polys}}]};
 }
 function approximation(kind){const o=kind==='original',a=o?C.approximation([1,2,2],-4,4,1):C.approximation([1,-1,1],-2,2,.5),formula=o?'x^2+2x+2':'x^2-x+1';
  const mid=a.start+a.step/2;
  return {id:`${kind}-approx`,family:'approx',kind,title:'Eine Funktion mit MLP und RBF annähern',purpose:o?'Aufgabe 3 · alle drei Teilaufgaben':'Anderes Intervall und andere Schrittweite selbst wählen',source:'2024, Aufgabe 3 · Folien 80, 99–104, 291–298',parts:[
   {id:'mlp',title:'a · MLP',recipes:['mlp'],prompt:T`Approximiere $f(x)=${formula}$ auf $[${a.start},${a.end}]$ mit einem dreischichtigen Perzeptron mit insgesamt $8\le n\le12$ Neuronen. Gib die Parameter an und zeichne die Näherung.`,clarification:'Die Eingabeschicht zählt mit. Die Musterlösung ist eine mögliche Konstruktion; andere korrekte Näherungen sind zulässig.',fields:[field('start',T`Startwert f(${a.start})`,a.ys[0]),field('delta',`Erstes Stufengewicht bei Schrittweite ${a.step}`,a.deltas[0]),field('theta','Ausgangsschwelle dieser Stufenkonstruktion',-a.ys[0])],solution:'',checks:['Stützwerte und Stufenunterschiede stimmen.','Alle Schwellen, Gewichte, Aktivierungen und der Startwert angegeben.','Neuronenzahl eingehalten und Graph gezeichnet.'],model:{coeff:a.coeff,start:a.start,end:a.end,step:a.step}},
   {id:'rbf',title:'b · RBF',recipes:['approx'],prompt:T`Approximiere dieselbe Funktion $f(x)=${formula}$ auf $[${a.start},${a.end}]$ mit einem RBF-Netz mit $8\le n\le12$ Neuronen. Gib alle Parameter an und zeichne die Näherung.`,fields:[field('radius','Radius bei neun gleichmäßig verteilten Zentren',a.step),field('middle',`Ausgabe der Dreieckskonstruktion bei x = ${mid}`,a.rbf(mid)),field('nodes','Gesamte Neuronenzahl dieser Konstruktion',11,{tolerance:0})],solution:'',checks:['Zentren, Distanzen, Radien, Aktivierungen und Ausgabegewichte angegeben.','Ein Zwischenpunkt und die Stützstellen kontrolliert.','Neuronenzahl und Zeichnung vollständig.']},
   {id:'verbessern',title:'c · Verbessern',recipes:['mlp','approx'],prompt:'Nenne mindestens zwei Möglichkeiten, die Approximationen zu verbessern.',fields:[],solution:'',checks:['Mindestens zwei konkrete Änderungen genannt.','Neuronengrenze und notwendige Anpassung der Gewichte berücksichtigt.']}
  ]};
 }
 function learning(kind){const o=kind==='original',initial=o?[{v:[5,4],label:'A'},{v:[7,5],label:'B'}]:[{v:[2,2],label:'A'},{v:[6,2],label:'B'}],points=o?[{name:'p',v:[1,6],label:'A'},{name:'q',v:[9,1],label:'B'}]:[{name:'p',v:[3,2],label:'B'},{name:'q',v:[4,4],label:'A'}],eta=.5,plain=C.lvq(initial,points,eta,'none'),supervised=C.lvq(initial,points,eta,'winner'),grid=[];
  for(let j=0;j<=(o?6:2);j++)for(let i=0;i<=(o?8:2);i++)grid.push({g:[i,j],v:[5*i,5*j]});const x=o?[28,20]:[8,6],somEta=o?.5:.4,sigma=o?2:1,som={data:C.som(grid,x,somEta,sigma)},neighbor=som.data.rows.find(r=>r.d2===2);
  const given=`Start: A=${v(initial[0].v)} gehört zur weißen Klasse A; B=${v(initial[1].v)} zur schwarzen Klasse B. Datenreihenfolge: ${points.map(p=>`${p.name}=${v(p.v)} aus Klasse ${p.label}`).join(', dann ')}. Lernrate η=0.5.`;
  return {id:`${kind}-learning`,family:'learning',kind,title:'LVQ und SOM: Vektoren verändern',purpose:o?'Aufgabe 4 · eine Epoche und das SOM-Gitter':'Falsche Gewinnerklasse und veränderte Winner-Wahl; kleineres SOM-Gitter',source:'2024, Aufgabe 4 · Folien 336, 340, 364–367',parts:[
   {id:'ohne',title:'a I · Ohne Klassen',recipes:['lvq'],prompt:given+' Berechne eine Epoche ohne Berücksichtigung der Klassen. Gib die Gesamtänderungen der Codebook-Vektoren an.',image:o?'exam_task_img_25.png':null,fields:[field('A','Endvektor A',plain.centers[0].v,{vector:true}),field('B','Endvektor B',plain.centers[1].v,{vector:true})],solution:'',checks:['Winner für jeden Punkt neu bestimmt.','Nur Winner verändert; beim zweiten Punkt aktuelle Vektoren verwendet.','Endwerte und Gesamtänderungen angegeben.'],model:{initial,points,eta,rule:'none'}},
   {id:'mit',title:'a II · Mit Klassen',recipes:['lvq'],prompt:given+' Berechne eine Epoche mit Berücksichtigung der Klassen. Beginne erneut mit den ursprünglichen Prototypen.',clarification:o?'Die Vorlage nennt keine eindeutige LVQ-Variante. Hier ist die Hauptrechnung die Gewinnerregel aus Folie 336. Die vollständige alternative Rechnung nach Folie 340 steht getrennt in der Lösung.':'Für diese Transferaufgabe gilt ausdrücklich die Gewinnerregel aus Folie 336: nur den nächsten Prototyp verändern, bei falscher Klasse abstoßen.',fields:[field('A','Endvektor A nach Gewinnerregel',supervised.centers[0].v,{vector:true}),field('B','Endvektor B nach Gewinnerregel',supervised.centers[1].v,{vector:true})],solution:'',checks:['Verwendete Regel klar benannt.','Vorzeichen anhand der Gewinnerklasse gewählt.','Für diesen Durchlauf neu gestartet und die Reihenfolge eingehalten.'],model:{initial,points,eta,rule:'winner'}},
   {id:'som',title:'b · SOM',recipes:['som'],prompt:T`Berechne die Änderungen der Codebook-Vektoren für $x=${v(x)}$, Lernrate $\eta=${somEta}$, euklidische Distanz und Gauß-Nachbarschaft mit Breite $\sigma=${sigma}$.`,clarification:o?T`Lesart der Abbildung: Jede Gitterkreuzung ist anfangs ein Prototyp $(5i,5j)$, $i=0,\ldots,8$, $j=0,\ldots,6$. Ein direkter Gitterschritt hat Abstand 1. Die Vorlage markiert die Neuronen nicht einzeln; diese Annahme wird für die vollständige Rechnung offengelegt.`:T`Neun Neuronen: Gitterindizes $i,j\in\{0,1,2\}$, Anfangsprototypen $(5i,5j)$. Ein direkter Gitterschritt hat Abstand 1. Bestimme den Winner selbst.`,image:o?'exam_task_img_28.png':null,figure:o?'':V.plane({range:[-1,12,-1,12],points:grid.map(r=>({x:r.v[0],y:r.v[1],label:v(r.g)})).concat([{x:x[0],y:x[1],label:'x'}]),title:'Anfangsprototypen mit Gitterindizes und Datenpunkt'}),fields:[field('winner','Alter Winner-Vektor',grid[som.data.winner].v,{vector:true}),field('new','Neuer Winner-Vektor',som.data.rows[som.data.winner].next,{vector:true}),field('diag',`Neuer Vektor des Neurons mit Gitterindex ${v(neighbor.g)}`,neighbor.next,{vector:true})],solution:'',checks:['Winner und Gitterindex bestimmt.','Gitterabstand und Datenraum getrennt.','Alle verlangten Änderungen mit derselben alten Gitterlage berechnet.'],model:{grid,x,eta:somEta,sigma}}
  ]};
 }
 function hopfield(kind){const o=kind==='original',W=o?[[0,-2,0],[-2,0,-2],[0,-2,0]]:[[0,1,-1],[1,0,2],[-1,2,0]],theta=o?[-1,-2,-1]:[0,1,-1],rows=C.hopfield(W,theta);
  return {id:`${kind}-hopfield`,family:'hopfield',kind,title:'Hopfield: alle erlaubten Übergänge',purpose:o?'Aufgabe 5 · Originalnetz':'Andere Verbindungen, Schwellen und Gleichheitsfälle',source:'2024, Aufgabe 5 · Folien 380–390',parts:[{id:'graph',title:'Zustandsgraph',recipes:['hopfield'],prompt:o?'Zeichne den vollständigen Zustandsgraphen des abgebildeten Hopfield-Netzes. Es ist keine Update-Reihenfolge festgelegt. Berücksichtige alle möglichen Nachfolgezustände.':T`Drei bipolare Neuronen mit symmetrischen Gewichten $w_{12}=1$, $w_{13}=-1$, $w_{23}=2$, Diagonale null und Schwellen $\theta=(0,1,-1)$. Zeichne den vollständigen Graphen aller möglichen asynchronen Einzelupdates.`,clarification:T`Zustandsreihenfolge $(u_1,u_2,u_3)$; bipolar. Schwellenregel: neuer Wert $+1$ bei $net_i\ge\theta_i$, sonst $-1$. ${o?'Die Kreiswerte werden als Schwellen gelesen: θ=(−1,−2,−1).':''}`,image:o?'exam_task_img_29.png':null,fields:[field('net','Netzeingaben bei −−−',rows[0].net,{vector:true}),field('next','Nachfolger von −−− bei Update nur von u₂ (drei Zahlen)',rows[0].next[1],{vector:true}),field('stable','Anzahl stabiler Zustände',rows.filter(r=>r.stable).length,{tolerance:0})],solution:'',checks:['Alle acht Ausgangszustände und 24 Einzelupdates erfasst.','Pro Übergang höchstens ein Neuron verändert.','Alle echten Pfeile und unveränderten Updates angegeben.','Stabile Zustände korrekt markiert.'],model:{W,theta}}]};
 }
 const tasks=['original','transfer'].flatMap(kind=>[tlu(kind),rbf(kind),approximation(kind),learning(kind),hopfield(kind)]);
 tasks.forEach(t=>t.parts.forEach(p=>{p.solution=W.render(t,p);}));
 const repairData=[
  ['tlu','Seite einer Geraden',T`Die Randgerade ist $x_1+x_2=4$. Die gewünschte Seite enthält $(1,1)$. Gib $(w_1;w_2;\theta)$ einer passenden TLU an.`,field('side','Gewichte und Schwelle',[-1,-1,-4],{vector:true,scale:true}),T`<p>Test mit $(1,1)$: $1+1=2\le4$. Also $-x_1-x_2\ge-4$. Gewichte $(-1,-1)$, Schwelle $-4$. Positive gemeinsame Skalierungen sind gleichwertig.</p>`,'tlu'],
  ['rbf','Radius eines Quadrats',T`Ein Quadrat reicht von $x_1=2$ bis $6$ und von $x_2=1$ bis $5$. Welchen Radius hat der $L_\infty$-Ball um seinen Mittelpunkt?`,field('radius','Radius',2),T`<p>Mittelpunkt: $c_1=(2+6)/2=4$, $c_2=(1+5)/2=3$, also $(4,3)$. Seitenlänge $6-2=4$, halbe Seitenlänge $4/2=2$. Der Radius ist deshalb $2$: Jede Koordinate darf höchstens $2$ vom Mittelpunkt abweichen.</p>`,'rbf'],
  ['approx','Höhe oder Stufenunterschied?',T`Ein MLP soll nacheinander die Höhen $7,4,6$ annehmen. Welches Ausgabegewicht gehört zum zweiten Sprung (von 4 auf 6)?`,field('delta','Ausgabegewicht',2),T`<p>$\Delta y=6-4=2$. Kontrolle: Start $7$, erster Sprung $-3$, zweiter Sprung $+2$: $7-3+2=6$.</p>`,'mlp'],
  ['learning','Nach dem ersten Update weiterrechnen',T`Nach dem ersten Datenpunkt steht der Winner bei $r=(3,5)$. Der nächste Punkt ist $q=(9,1)$, Lernrate $0.5$. Dieser Prototyp soll angezogen werden. Berechne seinen neuen Vektor.`,field('update','Neuer Vektor',[6,3],{vector:true}),T`<p>$r'= (3,5)+0.5[(9,1)-(3,5)]=(3,5)+(3,-2)=(6,3)$. Verwende den Stand nach dem ersten Update.</p>`,'lvq'],
  ['hopfield','Nur ein Neuron aktualisieren',T`Ausgang $s=(1,-1,-1)$. Für $u_2$ gilt $net_2=0$, $\theta_2=-2$. Berechne den Zustand nach genau diesem Einzelupdate.`,field('state','Neuer Zustand',[1,1,-1],{vector:true}),T`<p>$0\ge-2$, also wird $s_2=+1$. Die übrigen Werte bleiben gleich: $(1,1,-1)$.</p>`,'hopfield'],
  ['learning','Diagonal im Neuronengitter',T`Winner-Index $(2,1)$, Nachbar-Index $(1,2)$. Bestimme das quadrierte Gittermaß $d_G^2$.`,field('grid','d² im Gitter',2),T`<p>$d_G^2=(1-2)^2+(2-1)^2=1+1=2$. Dafür werden keine Datenraumkoordinaten benötigt.</p>`,'som']
 ];
 repairData.forEach(([family,title,prompt,q,solution,recipe],i)=>tasks.push({id:`repair-${i}`,family,kind:'repair',title,purpose:'Kurze Teilübung',source:recipes[recipe].source,parts:[{id:'schritt',title:'Ein Schritt',recipes:[recipe],prompt,fields:[q],solution,checks:['Rechnung ohne Vorlage nachvollzogen.']}]}));
 const families=[['tlu','1 · TLU-Fläche'],['rbf','2 · RBF-Fläche'],['approx','3 · Funktionsapproximation'],['learning','4 · LVQ und SOM'],['hopfield','5 · Hopfield']];
 root.NNContent={tasks,recipes,recipeHTML,table,detail,families};
 if(typeof module!=='undefined'&&module.exports)module.exports=root.NNContent;
})(typeof globalThis!=='undefined'?globalThis:this);
