/* Training formulations and separately identified verbatim statements from the supplied 2024 overview. */
(function(root){
 'use strict';
 const groups=[['a','Netztypen'],['b','TLU und Trennbarkeit'],['c','MLP und RBF'],['d','Training und Optimierer'],['e','Distanzen'],['f','Hopfield']];
 const rows=[
 ['a1','137, 171–183','Ein MLP mit differenzierbaren Aktivierungen kann mit Backpropagation trainiert werden.',true,'Backpropagation kann bei einem mehrschichtigen differenzierbaren Netz die Gewichtsgradienten berechnen.',true,'Die Kettenregel liefert die Gradienten. Ein erfolgreiches Finden des globalen Optimums ist damit nicht garantiert.'],
 ['a2','288–291','In Borgelts RBF-Netzen muss der Ausgang eine nichtlineare Schwellenaktivierung haben.',false,'In the RBF networks defined in the lecture, output neurons combine the hidden outputs linearly.',true,'Die nichtlinearen radialen Funktionen liegen in der verdeckten Schicht. Der Ausgang ist in dieser Definition linear.'],
 ['a3','336, 340','LVQ kann nach diesen Folien ausschließlich ohne Klasseninformation arbeiten.',false,'Die Folien beschreiben Vektorquantisierung sowohl ohne als auch mit Klasseninformation.',true,'Ohne Klassen wird angezogen. Mit Klassen werden je nach angegebener Regel passende Prototypen angezogen und unpassende abgestoßen.'],
 ['a4','359–366','SOM-Training berücksichtigt zusätzlich zum Winner eine Nachbarschaft zwischen Neuronen.',true,'SOM-Training garantiert für jeden Datensatz eine vollständig fehlerfreie Erhaltung aller Nachbarschaften.',false,'Die Gitter-Nachbarschaft fördert eine topologieerhaltende Abbildung. Das Trainingsziel ist keine Garantie einer perfekten Abbildung für jeden Datensatz.'],
 ['a5','380','Every neuron in the standard Hopfield network is both an input and an output neuron.',true,'Ein Standard-Hopfield-Netz besteht aus getrennten Eingabe-, Hidden- und Ausgabeschichten wie ein MLP.',false,'Im Hopfield-Netz sind alle Neuronen Ein- und Ausgabeneuronen; es gibt keine separate Hidden-Schicht.'],
 ['b1','17, 22–23','Die binären Eingaben eines TLU mit n Eingängen sind die 2ⁿ Ecken eines n-dimensionalen Würfels.',true,'Das Ausgabe-1-Gebiet eines TLU ist grundsätzlich ein begrenzter Würfel.',false,'Die binären Eingabepunkte liegen an Würfelecken. Für reelle Eingaben beschreibt w·x ≥ θ dagegen einen Halbraum.'],
 ['b2','24–27','Bei zwei binären Eingaben sind 14 der 16 booleschen Funktionen mit einer einzelnen TLU darstellbar.',true,'Bei zwei binären Eingaben sind mehr boolesche Funktionen nicht linear separierbar als linear separierbar.',false,'Nur XOR und XNOR sind nicht linear separierbar. Es bleiben 14 separierbare Funktionen.'],
 ['b3','26, 35','Zwei strikt linear separierbare endliche Punktmengen haben einen gemeinsamen Punkt ihrer konvexen Hüllen.',false,'For two finite point sets, disjoint convex hulls permit strict linear separation.',true,'Für endliche Mengen gilt die Äquivalenz. Ein gemeinsamer Hüllenpunkt verhindert strikte Trennung. Die Endlichkeitsbedingung nicht auf beliebige unendliche Mengen übertragen.'],
 ['b4','24–25','Eine einzelne TLU kann XOR auf zwei binären Eingaben darstellen.',false,'Für XOR genügt eine einzige trennende Gerade in der Ebene.',false,'Die positiv und negativ markierten Ecken liegen diagonal gegenüber. Keine Gerade trennt diese Klassen. Ein mehrschichtiges Netz kann die Aufgabe lösen.'],
 ['b5','17','Bei w·x = θ liefert Borgelts TLU die Ausgabe 1.',true,'A TLU produces an output proportional to its real-valued net input.',false,'Die TLU ist ein Schwellenwertschalter: 1 bei w·x ≥ θ, sonst 0. Am Gleichheitsfall gilt ebenfalls 1.'],
 ['c1','93','Mehrere ausschließlich affine Schichten ergeben insgesamt wieder eine affine Abbildung.',true,'Ein MLP mit ausschließlich affinen Schichten kann allein durch zusätzliche Tiefe beliebige nichtlineare Funktionen darstellen.',false,'Einsetzen ergibt A₂(A₁x+b₁)+b₂ = A₂A₁x+A₂b₁+b₂. Dafür entsteht keine Nichtlinearität. RBF-Basisfunktionen können nichtlineare Zusammenhänge darstellen.'],
 ['c2','104','Mit geeigneter Hidden-Aktivierung und genügend Neuronen kann ein MLP stetige Funktionen auf kompakten Mengen beliebig genau approximieren.',true,'Ein MLP mit fest vorgegebenen zwei Hidden-Neuronen kann jede stetige Funktion beliebig genau approximieren.',false,'Der Approximationssatz setzt geeignete Aktivierungen und hinreichend viele Neuronen voraus. Er behauptet keine beliebige Genauigkeit bei einer festen kleinen Neuronenzahl.'],
 ['c3','291','Eine Gauß-RBF wird außerhalb eines endlichen Radius exakt null.',false,'A Gaussian radial basis function is positive at every finite distance from its center.',true,'Gaußfunktionen fallen gegen null, erreichen aber bei endlichem Abstand nicht null. Rechteck- und Dreiecksaktivierungen können beschränkten Träger haben.'],
 ['c4','104, 173','Universelle Approximationsfähigkeit garantiert, dass Gradientenabstieg die passenden Gewichte findet.',false,'Der Approximationssatz ist eine Existenzaussage und keine Garantie für den Erfolg eines Trainingslaufs.',true,'Dass passende Gewichte existieren, beantwortet nicht, ob ein konkretes Trainingsverfahren sie findet.'],
 ['c5','300, 309–314','RBF-Training erfordert zwingend gleichzeitige Backpropagation durch alle Schichten mit identischer Lernrate.',false,'RBF-Zentren können zunächst durch Clustering bestimmt und die Ausgabegewichte anschließend separat angepasst werden.',true,'Die Folien behandeln eine getrennte Initialisierung und Anpassung. Eine einzige fest vorgeschriebene Trainingsstrategie gibt es nicht.'],
 ['d1','192','QuickProp verwendet eine lokale quadratische Näherung der Fehlerfunktion je Gewichtsrichtung.',true,'QuickProp ist gewöhnlicher Gradientenabstieg mit einer für alle Schritte unveränderten festen Schrittweite.',false,'QuickProp nutzt aktuelle und frühere Ableitungen für einen an einer Parabel orientierten Schritt. Praktische Schrittbegrenzungen bleiben möglich.'],
 ['d2','196','Adam verwendet Schätzungen des ersten und des unzentrierten zweiten Gradientenmoments.',true,'Adam speichert ausschließlich den aktuellen Gradienten und keine gleitenden Momente.',false,'Adam glättet Gradienten und quadrierte Gradienten und korrigiert üblicherweise deren anfänglichen Bias. Das unzentrierte zweite Moment ist nicht einfach die Varianz.'],
 ['d3','173','Gradientenabstieg auf einer nichtkonvexen Fehlerfläche ist grundsätzlich vor lokalen Minima geschützt.',false,'Ein kleiner oder verschwindender Gradient beweist nicht, dass ein globales Minimum erreicht wurde.',true,'Nichtkonvexe Fehlerflächen können lokale Minima und Sattelpunkte enthalten.'],
 ['d4','193','RProp nutzt das Vorzeichen partieller Ableitungen zur Bestimmung der Update-Richtung.',true,'Bei RProp ist die Schrittweite direkt proportional zum aktuellen Betrag der partiellen Ableitung.',false,'RProp trennt Richtung und Schrittweite. Die Richtung hängt vom Vorzeichen ab; Schrittweiten werden unter anderem anhand von Vorzeichenwechseln angepasst.'],
 ['d5','194','RMSProp glättet vergangene quadrierte Gradienten zur Skalierung der Updates.',true,'RMSProp und Adam verwenden genau dieselben Momentenschätzungen und sind dasselbe Verfahren.',false,'RMSProp verwendet ein gleitendes Mittel quadrierter Gradienten. Adam ergänzt insbesondere die Schätzung des ersten Moments.'],
 ['e1','332','Für eine Metrik gilt d(x,z) ≤ d(x,y)+d(y,z).',true,'Die Dreiecksungleichung fordert d(x,z) ≥ d(x,y)+d(y,z).',false,'Ein direkter Abstand ist höchstens so groß wie der Weg über einen dritten Punkt. Das Zeichen ist ≤.'],
 ['e2','332','Assoziativität gehört zu den definierenden Axiomen einer Metrik.',false,'Symmetrie d(x,y)=d(y,x) ist ein Metrikaxiom.',true,'Metriken erfüllen Nichtnegativität, Identität, Symmetrie und Dreiecksungleichung. Assoziativität ist kein zusätzliches Metrikaxiom.'],
 ['e3','332','Bei einer Metrik gilt d(x,y)=0 genau dann, wenn x=y.',true,'Eine Metrik darf verschiedenen Punkten Abstand 0 zuordnen.',false,'Der Abstand 0 kennzeichnet bei einer Metrik identische Punkte. Eine Pseudometrik wäre eine andere Definition.'],
 ['e4','332','Transitivität ist eines der Metrikaxiome.',false,'Aus d(x,y)=1 und d(y,z)=1 folgt zwingend d(x,z)=1.',false,'Transitivität betrifft Relationen. Die Dreiecksungleichung liefert hier lediglich d(x,z) ≤ 2; beispielsweise können x und z identisch sein.'],
 ['e5','289, 333','Manhattan- und Maximumdistanz gehören zur Minkowski-Familie.',true,'Für die Differenz (3,4) sind L₁=7, L₂=5 und L∞=4.',true,'L₁ summiert Beträge, L₂ verwendet die euklidische Länge, L∞ den größten Betrag. Der Grenzfall p→∞ ergibt die Maximumdistanz.'],
 ['f1','380','Ein Standard-Hopfield-Netz hat symmetrische Gewichte und Einsen auf der Hauptdiagonale.',false,'Standard Hopfield weights are symmetric and have a zero diagonal.',true,'Symmetrisch ist richtig. Die Diagonale ist null, weil die Standardneuronen keine Selbstkopplung haben.'],
 ['f2','380','Im Standard-Hopfield-Netz ist die Zahl verdeckter Neuronen gleich der positiven Zahl der Eingabeneuronen.',false,'Ein Hopfield-Netz mit drei Neuronen benötigt zusätzlich drei verdeckte Neuronen.',false,'Die drei Neuronen sind selbst Ein- und Ausgabeneuronen. Es gibt keine zusätzlichen Hidden-Neuronen.'],
 ['f3','388–390','Wenn man dasselbe Hopfield-Neuron sofort zweimal aktualisiert, springt es wegen symmetrischer Gewichte zum alten Wert zurück.',false,'Ohne Selbstkopplung und ohne zwischenzeitliche andere Updates liefert die sofortige erneute Aktualisierung desselben Neurons denselben Wert.',true,'Die Eingaben stammen von den unveränderten anderen Neuronen. Deshalb bleibt der Schwellenvergleich identisch; Symmetrie ist für diese einzelne Beobachtung nicht nötig.'],
 ['f4','83, 382','Bipolare und unipolare Zustandsdarstellungen können bei entsprechend angepassten Parametern ineinander umgerechnet werden.',true,'Für die Umrechnung von {0,1} nach {−1,+1} genügt s_bipolar=2s_unipolar−1; Gewichte und Schwellen dürfen in jedem Netz unverändert bleiben.',false,'Die Zustandsumrechnung stimmt. Zur Erhaltung derselben Netzfunktion müssen auch die Parameter passend umgerechnet werden.'],
 ['f5','388–390','Das Standard-Hopfield-Netz konvergiert bei zyklischer asynchroner Aktualisierung unter den angegebenen Schwellenregeln zu einem stabilen Zustand.',true,'Die Konvergenzaussage für asynchrone Updates garantiert auch bei gleichzeitiger Aktualisierung aller Neuronen einen stabilen Endzustand.',false,'Symmetrische Gewichte, Null-Diagonale und die Update-Konventionen gehören dazu. Synchrone Updates können Zyklen erzeugen. Ein stabiler Zustand ist kein garantiert globales Energieminimum.']
 ];
 const concepts=rows.map(([id,source,text,correct,alt,altCorrect,explanation])=>({id,group:id[0],source:'Folien '+source,forms:[{text,correct,explanation},{text:alt,correct:altCorrect,explanation}],core:true}));
 const extra=[
 ['lvq-two','336, 340','Bei der Regel von Folie 340 können zwei Prototypen im selben Lernschritt aktualisiert werden.',true,'Die zwei nächsten müssen verschiedene Klassen haben; eine muss zur Datenklasse passen. Dann richtigen anziehen und falschen abstoßen.'],
 ['som-grid','364','Der Gauß-Nachbarschaftsfaktor einer SOM verwendet den Abstand im Neuronengitter.',true,'Der Winner wird im Datenraum gefunden. Die Nachbarschaft benutzt anschließend die Gitterindizes.'],
 ['som-cut','364–367','Außerhalb von σ ist der Gauß-Nachbarschaftsfaktor automatisch null.',false,'Die Gaußfunktion bleibt positiv. Ein harter Abbruch benötigt eine zusätzliche Regel.'],
 ['old-weights','180–183','Beim Hidden-Fehler desselben Backpropagation-Schritts muss das bereits aktualisierte Ausgangsgewicht verwendet werden.',false,'Alle Ableitungen gehören zum bisherigen Parameterzustand. Erst nach ihrer Berechnung werden die Parameter aktualisiert.'],
 ['bias','17, 181','Ein Bias b entspricht der Schwelle θ=−b, wenn das Feld w·x−θ lautet.',true,'w·x+b und w·x−θ stimmen genau bei b=−θ überein.'],
 ['batch','44–49','Online- und Batch-Training liefern nach jeder Epoche zwingend dieselben Gewichte.',false,'Online verändert die Parameter nach einzelnen Beispielen. Batch sammelt bei festem Parameterstand.'],
 ['overfit','220–230','Ein kleiner Trainingsfehler garantiert gute Ergebnisse auf neuen Daten.',false,'Overfitting kann zu kleinem Trainingsfehler und großem Fehler auf neuen Daten führen.'],
 ['validation','220–230','Steigender Validierungsfehler bei sinkendem Trainingsfehler kann Overfitting anzeigen.',true,'Dieses Muster kann ein Anlass für Early Stopping sein. Es beweist keine feste optimale Neuronenzahl.'],
 ['softmax','164–170','Softmax-Ausgaben für endliche Eingaben sind positiv und summieren sich zu 1.',true,'Alle Exponentialwerte werden durch ihre gemeinsame Summe geteilt. Unabhängige Sigmoid-Ausgaben haben diese Summeneigenschaft nicht.'],
 ['bce','152–162','Für Ziel y=0 und Klassen-1-Wahrscheinlichkeit p lautet der BCE-Beitrag −ln p.',false,'Richtig ist −ln(1−p). −ln p gehört zum Ziel y=1.'],
 ['relu','253–255','ReLU hat bei negativen Eingaben die Ableitung 1.',false,'Dort ist die Ausgabe konstant 0 und die Ableitung 0. Bei positiven Eingaben ist die Ableitung 1.'],
 ['cnn-size','262–266','Ein 5×5-Bild mit 3×3-Kernel, Stride 1 und ohne Padding erzeugt eine 3×3-Ausgabe.',true,'Pro Richtung gilt (5−3)/1+1=3.'],
 ['energy-tie','385–390','Bei net=θ kann nach der ≥-Regel ein Wechsel von −1 zu +1 ohne Energieabnahme auftreten.',true,'ΔE=−(s_neu−s_alt)(net−θ)=0. Daher ist die Energie nicht bei jedem echten Wechsel strikt fallend.'],
 ['rbm','410–433','Eine Restricted Boltzmann Machine besitzt beliebige direkte Verbindungen zwischen sichtbaren Neuronen.',false,'Die Einschränkung verbietet Verbindungen innerhalb der sichtbaren und innerhalb der verdeckten Gruppe.'],
 ['fuzzy','458–497','Ein Fuzzy-Zugehörigkeitsgrad muss eine Wahrscheinlichkeit darstellen.',false,'Er beschreibt Zugehörigkeit zu einem unscharfen Begriff. Das ist nicht zwingend eine Ereigniswahrscheinlichkeit.']
 ];
 extra.forEach(([id,source,text,correct,explanation])=>concepts.push({id,group:'extra',core:false,source:'Folien '+source,forms:[{text,correct,explanation}]}));
 // Preserve wording, spelling and capitalization. Only PDF line wrapping is removed.
 // These are separate from forms[] so saved block answers retain their original question/answer mapping.
 const originalRows=[
  ['b2','For 2 Inputs, there are More Linearly Separable Combinations than Lineally Non-Separable Combinations',true],
  ['b3','In a 2 Class Problem, if the 2 classes are Linearly Separable, there exist atleast one point which is common to both Convex Hulls',false],
  ['f1','Has Symmetric Weights with 1s on the Diagonal',false],
  ['f2','No of Hidden Neurons equal to no of Input Neurons',false],
  ['f3','Updating One Value and Going to a new state, if it’s replaced immediately, it will go back to the previous state due to symmetry',false],
  ['f4','Bipolar and Unipolar equivalent in compute power',true],
  ['f5','Updating Nodes asynchronously without skipping will always lead to stability',true]
 ];
 originalRows.forEach(([id,text,correct])=>{const c=concepts.find(c=>c.id===id);c.original={text,correct,explanation:c.forms[0].explanation};});
 concepts.find(c=>c.id==='f3').original.explanation='„Replaced“ ist in der Vorlage ungenau. Bei der hier verwendeten Lesart wird dasselbe Neuron sofort erneut aktualisiert. Ohne Selbstkopplung kommen seine Eingaben weiterhin von den unveränderten anderen Neuronen. Es behält deshalb den gerade berechneten Wert; es springt nicht wegen der Symmetrie zurück.';
 concepts.find(c=>c.id==='f5').original.explanation='Gemeint ist das Standard-Hopfield-Netz mit festen symmetrischen Gewichten, Null-Diagonale und der angegebenen Schwellenregel. Werden die Neuronen asynchron immer wieder vollständig berücksichtigt, wird ein stabiler Zustand erreicht. Gleichzeitige Updates sind davon nicht erfasst; ein globales Energieminimum ist nicht garantiert.';
 const originalFragments=[
  ['a',['Multi-Layer Perceptron','Radial Basis Function Networks','Learning Vector Quantization','Self-Organizing Maps','Hopfield Networks']],
  ['b',['TLU with n inputs. n-dim hypercube.']],
  ['c',['MLPs (with linear activation functions) and RBFNs Compute Power comparison']],
  ['d',['Quick Prop','RMS Prop and Adam']],
  ['e',['Triangular','Associative','Transitive','Identity']]
 ];
 function question(concept,form=0){if(form==='original'&&concept.original)return {...concept,...concept.original,concept:concept.id,id:concept.id+'-original',form:'original',verbatim:true,source:'Aufgabenübersicht 2024 · Seite 4, Task 6 · Wortlaut der Vorlage; Erklärung: '+concept.source};return {...concept,...concept.forms[form%concept.forms.length],concept:concept.id,id:concept.id+'-'+(form%concept.forms.length),form:form%concept.forms.length,verbatim:false};}
 function next(memory,scope='core',current=null){const pool=concepts.filter(c=>scope==='original'?c.original:scope==='core'?c.core:scope==='extra'?!c.core:c.group===scope),total=Object.values(memory).reduce((s,m)=>s+(m.count||0),0);if(scope==='original'){const unseen=pool.find(c=>!memory[c.id]?.originalSeen&&c.id!==current);if(unseen)return unseen;}return [...pool].sort((a,b)=>{
   const score=c=>{const m=memory[c.id];if(!m)return 100;let s=m.lastCorrect?0:55;if(total-(m.seq||0)<3)s-=80;if(Date.now()-(m.at||0)>86400000)s+=25;if(c.id===current)s-=160;return s-Math.min(20,m.count||0);};return score(b)-score(a);
  })[0];}
 root.NNMC={groups,concepts,question,next,originalFragments};
 if(typeof module!=='undefined'&&module.exports)module.exports=root.NNMC;
})(typeof globalThis!=='undefined'?globalThis:this);
