'use strict';
courseModules.push({
 id:'theorie',title:'Weitere Folientheorie',source:'Folien 58–88, 199–243, 256–261, 340–357, 394–512',
 intro:'Diese Themen stehen in den Folien, sind aber in der Aufgabenübersicht von 2024 nicht als eigene Rechenaufgaben belegt. Nach den Kernaufgaben durcharbeiten und die Kontrollfragen beantworten.',
 goals:['Netztypen nach Struktur, Ausgabe und Lernziel unterscheiden.','Die zusätzlichen Verfahren aus den Folien erklären.','Voraussetzungen statt pauschaler Aussagen nennen.'],
 sections:[
  {id:'netztypen',title:'Netztypen & Lernen',source:'Folien 58–88, 288–290, 336, 359–366, 380–382',html:String.raw`
   <h2>Die drei Funktionen eines Neurons</h2><p>Die Netzeingabefunktion fasst eingehende Werte zusammen. Die Aktivierungsfunktion berechnet daraus einen Aktivierungswert, häufig unter Verwendung einer Schwelle. Die Ausgabefunktion erzeugt das weitergegebene Signal. Diese drei Schritte sind nicht automatisch dieselbe Funktion.</p>
   <table><thead><tr><th>Netz</th><th>Prinzip</th><th>Lern-/Anwendungsziel</th></tr></thead><tbody><tr><td>TLU</td><td>Gewichtete Summe, harte Schwelle</td><td>Binäre Entscheidung, Halbebenen</td></tr><tr><td>MLP</td><td>Vorwärtsgerichtete Schichten; nichtlineare Hidden-Aktivierungen</td><td>Regression oder Klassifikation</td></tr><tr><td>RBF</td><td>Abstände zu Zentren; radiale Aktivierungen; linearer Ausgang</td><td>Lokale Funktionsbausteine, Approximation</td></tr><tr><td>LVQ</td><td>Prototypen und datenabhängige Updates</td><td>Quantisierung, mit Labels auch Klassifikation</td></tr><tr><td>SOM</td><td>Prototypen mit Gitter-Nachbarschaft</td><td>Topologieerhaltende Abbildung</td></tr><tr><td>Hopfield</td><td>Rückkopplung, symmetrische Gewichte, keine Selbstkopplung</td><td>Assoziativer Speicher, Optimierung</td></tr></tbody></table>
   <p>Überwachtes Lernen verwendet Zielausgaben. Unüberwachtes Lernen sucht Struktur ohne solche Zielvorgaben. Online-Training aktualisiert nach einzelnen Beispielen; Batch-Training sammelt Beiträge bei unveränderten Parametern und aktualisiert anschließend.</p>
   <details><summary>Kontrollfrage: Ist RBF automatisch Klassifikation?</summary><p>Nein. Die Architektur ist nicht das Lernziel. Die lineare Ausgabe kann eine numerische Funktion approximieren oder als Teil einer Klassifikationslösung verwendet werden. Ebenso ist ein MLP nicht auf Klassen beschränkt.</p></details>`},
  {id:'training',title:'Training & Sensitivität',source:'Folien 171–217, 231–243',html:String.raw`
   <h2>Backpropagation ist die Kettenregel</h2><p>Ein Forward-Pass berechnet alle Ausgaben. Danach werden Fehlerfaktoren von hinten nach vorne bestimmt. Erst wenn alle Faktoren vorliegen, werden die Parameter verändert. Sonst vermischt man Ableitungen verschiedener Parameterzustände.</p>
   <p>Für quadratischen Fehler, logistische Aktivierung und identische Ausgabefunktion:</p>
   $$\delta_u=(t_u-o_u)o_u(1-o_u)\quad\text{am Ausgang},\qquad\delta_u=o_u(1-o_u)\sum_{s\in\mathrm{succ}(u)}w_{su}\delta_s\quad\text{innen}.$$
   $$\Delta w_{up}=\eta\delta_u o_p,\qquad\Delta\theta_u=-\eta\delta_u.$$
   <p>Die negative Schwellenänderung entspricht einer positiven Biasänderung, weil $b=-\theta$. Bei anderen Aktivierungen oder Fehlerfunktionen ändern sich die lokalen Ableitungsfaktoren.</p>
   <h2>Gewichte initialisieren und Netz verkleinern</h2><p>Gleiche Startgewichte können in gleich aufgebauten Hidden-Neuronen identische Ausgaben und Updates erzeugen. Unterschiedliche Initialisierungen brechen diese Symmetrie. Pruning entfernt Verbindungen oder Neuronen anhand ihres Beitrags und erfordert eine erneute Bewertung des Fehlers. Ein kleines Gewicht ist nur ein möglicher Hinweis; sein Einfluss hängt auch von Eingaben und Netzstruktur ab.</p>
   <h2>Sensitivitätsanalyse</h2><p>Die Ableitung einer Ausgabe nach einer Eingabe beschreibt die lokale Änderung der Ausgabe. In einem mehrschichtigen Netz wird sie ebenfalls über Kettenregel und Summation über die Verbindungswege berechnet. Eine große Ableitung bedeutet hohe lokale Empfindlichkeit, nicht automatisch eine kausale Bedeutung der Eingabe.</p>
   <details><summary>Kontrollfrage: Was garantiert das Training?</summary><p>Der universelle Approximationssatz garantiert Existenz geeigneter Netze unter seinen Voraussetzungen. Er garantiert weder, dass ein bestimmter Trainingslauf diese findet, noch eine bestimmte Generalisierung auf neue Daten.</p></details>`},
  {id:'autoencoder',title:'Autoencoder & CNN',source:'Folien 246–266',html:String.raw`
   <h2>Autoencoder</h2><p>Ein Encoder bildet Eingaben auf Merkmale ab; ein Decoder rekonstruiert daraus die Eingabe. Die Zielausgabe ist eine Kopie der ursprünglichen Eingabe. Ein Engpass mit weniger Hidden-Neuronen oder eine Beschränkung der aktiven Neuronen verhindert das einfache Durchreichen.</p>
   <p><strong>Denoising:</strong> Die Eingabe wird verrauscht, das Rekonstruktionsziel bleibt unverrauscht. <strong>Stacked Autoencoder:</strong> Zunächst Schicht für Schicht Merkmale lernen, anschließend die Encoder stapeln und das Netz gemeinsam nachtrainieren.</p>
   <h2>CNN</h2><p>Ein Kernel verarbeitet lokale Ausschnitte. Derselbe Kernel wird an unterschiedlichen Positionen verwendet: geteilte Gewichte. Mehrere Kernel erzeugen verschiedene Feature Maps. Pooling fasst Nachbarschaften zusammen, beispielsweise durch Maximum oder Mittelwert.</p>
   $$N_{out}=\left\lfloor\frac{N+2P-K}{S}\right\rfloor+1.$$
   <p>Hier: Eingabelänge $N$, Padding $P$, Kernelgröße $K$, Stride $S$; jede Achse wird separat gerechnet. Beispiel: $N=5,K=3,P=0,S=1$ liefert 3, also bei einem quadratischen Bild eine 3×3-Feature-Map. Ein 2×2-Pooling mit Stride 2 ergibt ohne Padding eine 1×1-Ausgabe; übrige Randwerte werden nicht zu einem vollen Fenster.</p>
   <details><summary>Kontrollfrage: Warum weniger Parameter?</summary><p>Ein vollverbundenes Neuron hätte ein Gewicht pro Eingabewert. Ein CNN-Filter benutzt nur seine lokale Kernelmatrix und teilt diese Parameter über alle Positionen. Die Zahl der Positionen vergrößert daher die Zahl der Ausgabewerte, aber nicht die Zahl der Gewichte dieses Filters.</p></details>
   <p><a href="#/deeplearning/cnn">Faltungsschritte im Simulator</a></p>`},
  {id:'em',title:'LVQ-Fenster & EM',source:'Folien 340–357',html:String.raw`
   <h2>Überwachte LVQ-Regel der Folien</h2><p>Betrachte die zwei nächsten Prototypen. Haben sie verschiedene Labels und ist eines davon das Label des Datenpunktes, wird der richtige angezogen und der falsche abgestoßen. Diese Regel ist ausdrücklich von einer Variante zu unterscheiden, die nur den Gewinner verändert.</p>
   <p>Die zusätzliche Window-Regel beschränkt Updates auf Punkte nahe der Entscheidungsgrenze:</p>
   $$\min\left(\frac{d_j}{d_k},\frac{d_k}{d_j}\right)>\frac{1-\xi}{1+\xi}.$$
   <p>Beispiel: $d_j=2,d_k=3,\xi=0.2$. Links steht $2/3$, rechts ebenfalls $2/3$. Wegen der <strong>strikten</strong> Ungleichung findet kein Update statt. Verwende hier die Distanzen, nicht unbemerkt ihre Quadrate.</p>
   <h2>Von harten zu weichen Zuordnungen</h2><p>c-Means ordnet einen Punkt einem Cluster zu. Bei einem Gauß-Mischmodell kann jeder Punkt mit unterschiedlichem Gewicht zu mehreren Komponenten gehören. Die Gewichte ergeben sich aus den Mischungsanteilen und den Dichten am Datenpunkt.</p>
   <ol><li><strong>E-Schritt:</strong> Mit den aktuellen Parametern die Zugehörigkeitswahrscheinlichkeiten jedes Datenpunktes zu allen Komponenten berechnen.</li><li><strong>M-Schritt:</strong> Mit diesen Gewichten die Komponentenparameter durch gewichtete Maximum-Likelihood-Schätzung neu bestimmen.</li><li>Beide Schritte wiederholen.</li></ol>
   <p>Beispiel für zwei Komponenten: Unnormierte Beiträge 0.12 und 0.08 ergeben Zugehörigkeiten 0.6 und 0.4. Beide summieren sich zu 1. Soft-LVQ überträgt diese weiche Zuordnung auf ein Online-Verfahren.</p>
   <details><summary>Kontrollfrage: Werden im E-Schritt schon Zentren verschoben?</summary><p>Nein. Im E-Schritt werden die Gewichte der Datenpunkte aus dem aktuellen Modell ermittelt. Die Parameteranpassung mit diesen Gewichten ist der M-Schritt.</p></details>`},
  {id:'boltzmann',title:'Speicher & Boltzmann',source:'Folien 394–433',html:String.raw`
   <h2>Hebbscher Speicher</h2><p>Für ein bipolares Muster $s$ setzen wir außerhalb der Diagonale $w_{ij}=s_i s_j$, auf der Diagonale 0. Gleiche Vorzeichen ergeben +1, verschiedene −1. Bei mehreren Mustern werden solche Beiträge addiert. Ob alle gewünschten Muster stabil sind, muss anschließend geprüft werden; Störungen zwischen Mustern können die Speicherung beeinträchtigen.</p>
   <p>Beispiel $s=(1,-1,1)$: $w_{12}=-1$, $w_{13}=1$, $w_{23}=-1$. Bei Schwellen 0 ist $Ws=(2,-2,2)$ und das Muster stabil. Auch sein negatives Muster ist stabil.</p>
   <h2>Lokales statt globales Minimum</h2><p>Die Hopfield-Dynamik kann in einem lokalen Minimum enden. Eine Energieabnahme bedeutet daher nicht, dass ein global optimales Ergebnis erreicht wird. Simulated Annealing lässt temperaturabhängig auch ungünstige Schritte zu und senkt die Temperatur allmählich.</p>
   <h2>Boltzmann-Maschine</h2><p>Einem Zustand wird die Wahrscheinlichkeit $P(s)=Z^{-1}\exp[-E(s)/(kT)]$ zugeordnet. $Z$ normiert die Verteilung. Bei gleicher Temperatur sind Zustände mit kleinerer Energie wahrscheinlicher. Anders als beim deterministischen Hopfield-Update werden Zustände probabilistisch aktualisiert.</p>
   <p>Boltzmann-Maschinen können sichtbare und verdeckte Neuronen enthalten. In einer Restricted Boltzmann Machine fehlen Verbindungen innerhalb beider Gruppen; Verbindungen zwischen den Gruppen sind symmetrisch. Das erleichtert abwechselnde Updates.</p>
   <h2>Trainingsidee der RBM</h2><p>Daten an den sichtbaren Neuronen festhalten, Hidden-Zustände bestimmen, sichtbare Daten rekonstruieren und daraus erneut Hidden-Zustände bestimmen. Das Gewichtsupdate vergleicht Daten- und Rekonstruktionskorrelation:</p>
   $$\Delta W=\eta(xy^\top-x^*(y^*)^\top).$$
   <details><summary>Kontrollfrage: Ist jede niedrige Energie ein gespeichertes Muster?</summary><p>Nein. Unerwünschte stabile Zustände können entstehen. Man muss die gewünschten Muster und ihre Einzugsgebiete getrennt von anderen Attraktoren betrachten.</p></details>`},
  {id:'rekurrent',title:'Rekurrente Netze',source:'Folien 434–456',html:String.raw`
   <h2>Rückkopplung modelliert einen zeitlichen Zustand</h2><p>In den Folien werden dynamische Systeme wie Abkühlung, Federbewegung und Bahnkurven betrachtet. Eine Differentialgleichung kann über kleine Zeitschritte näherungsweise als wiederholtes Netzwerkupdate ausgeführt werden.</p>
   <p>Abkühlung: $\dot\vartheta=-k(\vartheta-\vartheta_A)$. Ein expliziter Zeitschritt liefert</p>
   $$\vartheta_{t+\Delta t}=\vartheta_t-k\Delta t(\vartheta_t-\vartheta_A).$$
   <p>Beispiel: $\vartheta_t=30$, $\vartheta_A=20$, $k=0.1$, $\Delta t=0.5$. Dann $\vartheta_{neu}=29.5$. Der nächste Schritt startet bei diesem neuen Wert.</p>
   <h2>Höhere Ordnung in ein System erster Ordnung übersetzen</h2><p>Für $\ddot x=f(t,x,\dot x)$ setze $v=\dot x$. Dann $\dot x=v$, $\dot v=f(t,x,v)$. Dadurch können die benötigten Zustandsgrößen getrennt gespeichert werden.</p>
   <h2>Backpropagation through Time</h2><p>Die wiederholte Berechnung wird über die Zeitschritte entfaltet. Danach kann die Kettenregel wie in einem Feedforward-Netz angewendet werden. Dieselben Parameter werden zu mehreren Zeitpunkten benutzt; ihre Gradientenbeiträge müssen zusammengeführt werden.</p>
   <details><summary>Kontrollfrage: Sind das unabhängige Gewichte je Zeitpunkt?</summary><p>Nein. Die entfalteten Kopien stellen denselben dynamischen Prozess dar. Zeitlich geteilte Parameter erhalten Beiträge aus allen Stellen, an denen sie verwendet wurden.</p></details>`},
  {id:'fuzzy',title:'Fuzzy & Neuro-Fuzzy',source:'Folien 457–497, 512',html:String.raw`
   <h2>Zugehörigkeit statt harter Mitgliedschaft</h2><p>Eine Fuzzy-Menge wird durch $\mu(x)\in[0,1]$ beschrieben. Dieser Zugehörigkeitsgrad ist nicht automatisch eine Wahrscheinlichkeit. Eine t-Norm verknüpft „und“, eine t-Conorm „oder“. Häufige Beispiele sind Minimum und Maximum; auch andere in den Folien definierte Operatoren sind möglich.</p>
   <p>Mit Standardnegation, Minimum und Maximum: Für Zugehörigkeiten 0.3 und 0.7 ist die Negation von 0.3 gleich 0.7, die Konjunktion 0.3 und die Disjunktion 0.7.</p>
   <h2>Regelausgabe</h2><p>Mamdani–Assilian-Regeln liefern Fuzzy-Mengen als Konklusion. Diese werden zusammengeführt und defuzzifiziert. COG ist der Schwerpunkt, COA halbiert die Fläche, MOM mittelt die Punkte maximaler Zugehörigkeit. Diese drei Orte müssen nicht übereinstimmen.</p>
   <p>TSK-Regeln liefern Funktionen der Eingaben. Bei Aktivierungen $a_i$ und Funktionswerten $f_i$ ist die Ausgabe $\sum_i a_i f_i/\sum_i a_i$, sofern der Nenner positiv ist. Beispiel: Aktivierungen $(0.2,0.8)$ und Ausgaben $(10,20)$ ergeben 18.</p>
   <h2>Regeln als trainierbares Netz</h2><p>Neuro-Fuzzy-Systeme stellen Zugehörigkeitsfunktionen, Regelverknüpfungen und Ausgabebildung als Netz dar. ANFIS verwendet TSK-Regeln. NEFCLASS verwendet Regeln zur Klassenvorhersage. Lernen verändert die Parameter; Einschränkungen sollen die interpretierbare Bedeutung der Mengen und Regeln erhalten.</p>
   <p>Die NEFCLASS-Abfolge in den Folien: Fuzzy-Partitionen initialisieren, Regeln erzeugen und auswählen, Zugehörigkeitsfunktionen trainieren, überflüssige Regeln entfernen. Ziel sind nachvollziehbare Regeln; eine vollständig automatische Modellwahl wird auf Folie 512 ausdrücklich nicht zugesagt.</p>
   <details><summary>Kontrollfrage: Warum beschränkt man die Anpassung?</summary><p>Eine rechnerisch bessere Fehlerfunktion allein genügt nicht, wenn trainierte Zugehörigkeitsfunktionen anschließend ihre sprachliche Bedeutung verlieren. Die semantischen Bedingungen des ursprünglichen Modells sollen erhalten bleiben.</p></details>`}
 ]
});
