import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.NN_TEST_URL||'http://127.0.0.1:8766/';
const browser=await chromium.launch({channel:'msedge',headless:true}),errors=[];
try{
 await fs.mkdir('tmp',{recursive:true});
 for(const width of [1400,390]){
  const context=await browser.newContext({viewport:{width,height:950}}),page=await context.newPage();
  page.on('pageerror',e=>errors.push(e.message));
  const stored=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ann_exam_focus_v1')));
  await page.goto(base+'#/fragen',{waitUntil:'networkidle'});
  await page.getByRole('link',{name:'Klausurfragen üben',exact:true}).click();
  await page.locator('[data-exam-question="original-block-b"]').waitFor();
  assert.equal(await page.locator('[data-exam-language="de"]').getAttribute('aria-pressed'),'true');
  assert.ok(await page.locator('#exam-back').isDisabled());
  assert.equal(await page.locator('legend').count(),2);
  assert.match(await page.locator('legend').first().innerText(),/Bei zwei Eingängen/);
  await page.locator('[data-answer="b2-original"][value="true"]').check();
  const pending=await stored();
  await page.getByRole('button',{name:'Original (Englisch)',exact:true}).click();
  assert.deepEqual((await stored()).learning.attempts,pending.learning.attempts);
  assert.deepEqual((await stored()).mc,pending.mc);
  assert.ok(await page.locator('[data-answer="b2-original"][value="true"]').isChecked());
  assert.match(await page.locator('legend').first().innerText(),/For 2 Inputs, there are More/);
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('[data-exam-language="en"]').getAttribute('aria-pressed'),'true');
  assert.ok(await page.locator('[data-answer="b2-original"][value="true"]').isChecked());
  await page.locator('[data-answer="b3-original"][value="false"]').check();
  await page.locator('#question-submit').click();
  assert.match(await page.locator('.feedback').innerText(),/2 \/ 2 richtig/);
  assert.doesNotMatch(await page.locator('.feedback').innerText(),/Punkte/);
  assert.equal(await page.locator('.answer-explanation[lang="en"]').count(),2);
  const graded=await stored();
  await page.getByRole('button',{name:'Deutsch',exact:true}).click();
  assert.equal(await page.locator('.answer-explanation[lang="de"]').count(),2);
  assert.deepEqual((await stored()).mc,graded.mc);
  await page.locator('#exam-next').click();
  assert.equal(await page.locator('[data-exam-question]').getAttribute('data-exam-question'),'original-block-f');
  assert.ok(await page.locator('#exam-next').isDisabled());
  assert.equal(await page.locator('legend').count(),5);
  await page.getByRole('button',{name:'Original (Englisch)',exact:true}).click();
  const expected=await page.evaluate(()=>NNQuestions.get('original-block-f').options);
  assert.deepEqual(await page.locator('legend').allTextContents(),expected.map((o,i)=>`${i+1}. ${o.text}`));
  for(const o of expected)await page.locator(`[data-answer="${o.id}"][value="${o.correct}"]`).check();
  await page.locator('#question-submit').click();
  assert.match(await page.locator('.feedback').innerText(),/5 \/ 5 Punkte/);
  const finished=await stored();
  await page.reload({waitUntil:'networkidle'});
  assert.equal(await page.locator('[data-exam-question]').getAttribute('data-exam-question'),'original-block-f');
  assert.deepEqual((await stored()).mc,finished.mc);
  await page.locator('#exam-back').click();
  assert.match(await page.locator('.feedback').innerText(),/2 \/ 2 richtig/);
  await page.locator('#exam-retry').click();
  assert.equal(await page.locator('.answer-explanation').count(),0);
  await page.locator('[data-answer="b3-original"][value="skip"]').check();
  await page.getByRole('link',{name:'Grundlage nachlesen',exact:true}).click();
  await page.getByRole('link',{name:'← Zur Bearbeitung zurück'}).first().click();
  assert.equal(new URL(page.url()).hash,'#/mc/klausur');
  assert.ok(await page.locator('[data-answer="b3-original"][value="skip"]').isChecked());
  assert.equal((await stored()).learning.attempts.at(-1).helped,true);
  await page.getByRole('button',{name:'Deutsch',exact:true}).click();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.screenshot({path:`tmp/exam-mc-${width}.png`,fullPage:true});
  await page.goto(base+'#/mc/ueben');
  assert.equal(await page.locator('[data-exam-language]').count(),0);
  assert.equal(await page.locator('[data-exam-question]').count(),0);
  await context.close();
 }
 assert.deepEqual(errors,[]);
 console.log('PASS: original-only route, EN/DE, pending/submitted answer persistence, unchanged grading, reload, retry, theory return, desktop/mobile.');
}finally{await browser.close();}
