import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.NN_TEST_URL||'http://127.0.0.1:8766/';
const browser=await chromium.launch({channel:'msedge',headless:true});const errors=[];
const context=await browser.newContext({viewport:{width:1400,height:1000},acceptDownloads:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
const go=async path=>{await page.goto(base+'#/'+path);await page.waitForTimeout(120);};
const stored=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('ann_exam_focus_v1')));
try{
 await page.goto(base+'#/theorie',{waitUntil:'networkidle'});assert.equal(await page.locator('.theory-toc li').count(),10);assert.equal(await page.locator('nav[aria-label="Hauptnavigation"] a').count(),4);
 const ids=await page.evaluate(()=>NNTheory.chapters.map(c=>c.id));
 for(const width of [1400,390]){await page.setViewportSize({width,height:950});for(const id of ids){await go('theorie/'+id);assert.equal(await page.locator('.katex-error').count(),0,id);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),id);assert.ok(await page.locator('.reading-section').count()>=3);}}
 await page.setViewportSize({width:1400,height:1000});await go('theorie/netze/schwelle');await page.waitForTimeout(300);assert.equal((await stored()).learning.reading.positions.netze.section,'schwelle');await page.locator('#chapter-read').check();await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(250);assert.ok(await page.locator('#chapter-read').isChecked());assert.ok(Math.abs(await page.locator('#read-schwelle').evaluate(el=>el.getBoundingClientRect().top)-24)<8);
 await go('theorie');assert.match(await page.locator('.theory-start').innerText(),/An deiner Lesestelle weiter/);
 // Reading every answer does not create graded attempts or MC memory.
 const before=await stored();await go('fragen');await page.locator('#catalog-answers').check();assert.equal(await page.locator('.catalog-question').count(),110);assert.equal(await page.locator('.catalog-option details').count(),0);assert.equal(await page.locator('.katex-error').count(),0);let after=await stored();assert.deepEqual(after.mc,before.mc);assert.deepEqual(after.learning.attempts,before.learning.attempts);
 const expected=await page.evaluate(()=>NNQuestions.all.flatMap(q=>NNQuestions.options(q)).filter(o=>!o.correct).length);assert.equal(await page.locator('.corrected').count(),expected);
 await page.locator('#catalog-origin').selectOption('original');assert.equal(await page.locator('.catalog-question').count(),9);await page.locator('#catalog-type').selectOption('block');assert.equal(await page.locator('.catalog-question').count(),2);assert.equal(await page.locator('.catalog-option').count(),7);
 await page.locator('#catalog-topic').selectOption('hopfield');assert.equal(await page.locator('.catalog-option').count(),5);
 await page.locator('.catalog-question .button').click();assert.equal(await page.locator('[data-answer]').count(),15);assert.equal(await page.locator('.answer-explanation').count(),0);
 const question=await page.evaluate(()=>NNQuestions.get('original-block-f'));for(const o of question.options)await page.locator(`[data-answer="${o.id}"][value="${o.correct}"]`).check();await page.locator('#question-submit').click();assert.match(await page.locator('.feedback').innerText(),/5 \/ 5 Punkte/);assert.equal((await stored()).mc.f5.originalSeen,true);
 // A frozen answer is not graded again by Back, Next, reload, or catalog reading.
 await go('mc/frage/b2-original');await page.locator('[data-mc="true"]').click();const answered=await stored();const qid=await page.locator('[data-question]').getAttribute('data-question');await page.locator('#mc-next').click();const nextid=await page.locator('[data-question]').getAttribute('data-question');await page.locator('#mc-back').click();assert.equal(await page.locator('[data-question]').getAttribute('data-question'),qid);assert.ok(await page.locator('[data-mc="true"]').isDisabled());await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('[data-question]').getAttribute('data-question'),qid);assert.deepEqual((await stored()).mc,answered.mc);await page.locator('#mc-next').click();assert.equal(await page.locator('[data-question]').getAttribute('data-question'),nextid);
 // Explicit retry adds a new attempt without overwriting the old one.
 await go('mc/frage/b2-original');const oldAttempt=(await stored()).learning.attempts.findLast(a=>a.qid==='b2-original');await page.locator('#mc-retry').click();await page.locator('[data-mc="false"]').click();after=await stored();assert.deepEqual(after.learning.attempts.find(a=>a.id===oldAttempt.id),oldAttempt);assert.equal(after.mc.b2.count,answered.mc.b2.count+1);
 // Choice variant allows several simultaneous correct selections and explains every option.
 await go('mc/frage/softmax-zahlen');await page.locator('[data-answer="softmax-zahlen-o0"]').check();await page.locator('[data-answer="softmax-zahlen-o1"]').check();await page.reload({waitUntil:'networkidle'});assert.ok(await page.locator('[data-answer="softmax-zahlen-o1"]').isChecked());await page.locator('#question-submit').click();assert.match(await page.locator('.feedback').innerText(),/3 \/ 3/);assert.equal(await page.locator('.answer-explanation').count(),3);assert.doesNotMatch(await page.locator('.feedback').innerText(),/\d \/ \d Punkte/);
 // Every new scenario, selection and original block supports answering and complete feedback.
 const newqs=await page.evaluate(()=>NNQuestions.all.filter(q=>q.provenance==='variant').map(q=>({id:q.id,type:q.type,options:q.options.map(o=>({id:o.id,correct:o.correct}))})));
 for(const width of [1400,390]){await page.setViewportSize({width,height:950});for(const q of newqs){await go('mc/frage/'+q.id);if(await page.locator('#mc-retry').count())await page.locator('#mc-retry').click();for(const o of q.options){if(q.type==='select'){if(o.correct)await page.locator(`[data-answer="${o.id}"]`).check();}else await page.locator(`[data-answer="${o.id}"][value="${o.correct}"]`).check();}await page.locator('#question-submit').click();assert.equal(await page.locator('.answer-explanation').count(),q.options.length);assert.match(await page.locator('.feedback').innerText(),new RegExp(`${q.options.length} / ${q.options.length}`));assert.equal(await page.locator('.katex-error').count(),0,q.id);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),q.id);}}
 // Theory detour preserves a pending answer and returns to its exact attempt.
 await go('mc/frage/som-nachbar');await page.locator('#mc-retry').click();await page.locator('[data-answer="som-nachbar-o0"][value="true"]').check();const pending=(await stored()).learning.attempts.at(-1);await page.getByRole('link',{name:'Erklärung zu diesem Thema öffnen'}).click();await page.getByRole('link',{name:'← Zur Bearbeitung zurück'}).first().click();assert.equal((await stored()).learning.attempts[(await stored()).learning.cursor].id,pending.id);assert.ok(await page.locator('[data-answer="som-nachbar-o0"][value="true"]').isChecked());assert.equal((await stored()).learning.attempts.at(-1).helped,true);
 // Catalog detour returns to the same filter and scroll position.
 await go('fragen');await page.locator('#catalog-origin').selectOption('variant');await page.locator('#catalog-type').selectOption('all');await page.locator('#catalog-topic').selectOption('all');await page.locator('.catalog-question').nth(4).scrollIntoViewIfNeeded();await page.locator('.catalog-question').nth(4).getByRole('link',{name:'Grundlage nachlesen'}).click();const catalogY=(await stored()).learning.returnY;await page.getByRole('link',{name:'← Zur Bearbeitung zurück'}).first().click();assert.equal(await page.locator('#catalog-origin').inputValue(),'variant');assert.ok(Math.abs(await page.evaluate(()=>scrollY)-catalogY)<10);
 // Moving on without answering must actually choose a different variant, without grading the unfinished one.
 await go('mc');await page.locator('#mc-scope').selectOption('variants');const unseenId=await page.locator('[data-question]').getAttribute('data-question'),unanswered=await stored();await page.locator('#mc-next').click();assert.notEqual(await page.locator('[data-question]').getAttribute('data-question'),unseenId);assert.deepEqual((await stored()).mc,unanswered.mc);await page.locator('#mc-back').click();assert.equal(await page.locator('[data-question]').getAttribute('data-question'),unseenId);
 // Original task input survives a theory detour.
 await go('training/original-learning/som');await page.locator('#work').evaluate(e=>e.open=true);await page.locator('#work-note').fill('Winner noch prüfen');await page.locator('.task-theory-link a').click();assert.match(page.url(),/theorie\/som/);await page.getByRole('link',{name:'← Zur Bearbeitung zurück'}).first().click();assert.equal(await page.locator('#work-note').inputValue(),'Winner noch prüfen');
 // Starting a second exam block preserves the first, including unsubmitted answers.
 await go('mc');await page.locator('#exam-block-controls').evaluate(e=>e.open=true);await page.locator('#mc-five').click();const firstId=await page.locator('[data-block]').first().getAttribute('data-block');await page.locator(`[data-block="${firstId}"][value="true"]`).check();await go('mc');await page.locator('#exam-block-controls').evaluate(e=>e.open=true);await page.locator('#mc-thirty').click();assert.equal((await stored()).mcBlockHistory[0].answers[firstId],'true');await go('mc/verlauf');await page.locator('a[href="#/mc/block/0"]').click();assert.ok(await page.locator(`[data-block="${firstId}"][value="true"]`).isChecked());await page.locator('#block-finish').click();assert.equal((await stored()).mcBlockHistory[0].finished,true);assert.equal((await stored()).mcBlock.finished,false);
 // Full export/import of history, drafts, theory position and filters. Invalid imports are atomic.
 await go('quellen');const promise=page.waitForEvent('download');await page.locator('#export').click();const download=await promise,buf=await fs.readFile(await download.path()),payload=JSON.parse(buf);await page.locator('#import').setInputFiles({name:'learning.json',mimeType:'application/json',buffer:buf});assert.match(await page.locator('#data-message').innerText(),/Importiert/);assert.deepEqual((await stored()).learning,payload.state.learning);
 const beforeInvalid=await stored();payload.state.learning.attempts[0].qid='not-a-question';await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});assert.match(await page.locator('#data-message').innerText(),/nicht durchgeführt/);assert.deepEqual(await stored(),beforeInvalid);
 // Old storage (before learning history existed) migrates a graded active question without counting it again.
 const ctx=await browser.newContext();const p=await ctx.newPage();await p.goto(base+'#/');await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('ann_exam_focus_v1'));delete s.learning;s.mcScope='core';s.mcActive={concept:'b2',form:0,answer:'true'};s.mc={b2:{count:19,lastCorrect:true,at:1,seq:1}};localStorage.setItem('ann_exam_focus_v1',JSON.stringify(s));});await p.reload({waitUntil:'networkidle'});await p.goto(base+'#/mc');assert.ok(await p.locator('[data-mc="true"]').isDisabled());assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('ann_exam_focus_v1')).mc.b2.count),19);await ctx.close();
 await page.setViewportSize({width:1400,height:1000});await go('theorie/netze/zahlen');await page.screenshot({path:'tmp/theory-reading-desktop.png'});await page.setViewportSize({width:390,height:844});await go('theorie/netze/schwelle');await page.screenshot({path:'tmp/theory-reading-mobile.png'});await go('fragen/original');await page.screenshot({path:'tmp/catalog-mobile.png'});
 assert.deepEqual(errors,[]);console.log('PASS: 10 chapters at both widths, 110 catalog entries, all explanations, reading positions, original groups, all 14 variants, stable history/retry/reload, theory detours, legacy migration and export/import.');
}finally{await browser.close();}
